### DISCUSSION TITLE
Make features a clickable link in home layout

### DISCUSSION THREAD

**Discussion by MarkusKeck** [vuejs/vitepress#1072] [Ideas]
At the moment the features dont have any functionality except for displaying some text.
It would be great if the features could be an actual clickable element.

```yml
features:
  - title: not clickable
    details: some text
    
  - title: clickable feature
    details: Lorem ipsum...
    link: /vitepress-example
```
