### DISCUSSION TITLE
Lists - no padding, no leveling?

### DISCUSSION THREAD

**Discussion by goozoon** [vuejs/vitepress#1665] [Ideas]
We we have no padding for the lists, nor in vuepress, nor in vitepress?
With padded list (first level padding) it looks much cleaner (word, github...)

I saw different bullets in vuepress, but not in vitepress for list leveling.

Also tittle padding is very different, too. With massive gap under `Main title`

List test - Github markdown
---

# Main title
## Second level title

Some simple text in this place to be here

* Line ranges: `{5-8}`
* Multiple single lines: `{4,7,9}`
  * One time piece of the line
  * Another one is ok
    * One two three
    * Three two one
* Combined: {4,7-13,16,23-27,40}

List ended

---
List test - vitepress (copy paste from here to vitepress)

![vitepress-lists](https://user-images.githubusercontent.com/48757340/205304665-a6c61d8d-fb2e-4077-8c60-596bac503a48.png)

**Comment by goozoon** [comment]
Should i better create [feature request](https://github.com/vuejs/vitepress/issues/new?template=feature_request.yml) ?

**Reply by brc-dd** [reply]
It is customisable using CSS. Will need only 4-5 lines IG.

**Reply by goozoon** [reply]
understand, but wouldn't it make sense to make it as default for everyone? please

**Comment by goozoon** [comment]
any chance to add characters for unsorted lists? please

even this HTML

```html
<ul>
  <li>First item</li>
  <li>Second item</li>
  <li>Third item
    <ul>
      <li>Indented item</li>
      <li>Indented item</li>
    </ul>
  </li>
  <li>Fourth item</li>
</ul>
```

give all dots, only

**Reply by brc-dd** [reply]
You need some CSS like this to make it work:

```css
ul { list-style: disc; }
ul ul { list-style: circle; }
ul ul ul { list-style: square; }
```

**Reply by goozoon** [reply]
yes, for `.vp-doc`

```css
.vp-doc ul { list-style: disc; }
.vp-doc ul ul { list-style: circle; }
.vp-doc ul ul ul { list-style: square; }
```

But still... what about to have these out of the box?

Like this: https://github.com/vuejs/vitepress/commit/c184ec947113087de66884578319f9fb4089fbb1

Could it be, please?
