### DISCUSSION TITLE
make the content container wider when there is no sidebar

### DISCUSSION THREAD

**Discussion by xu4wang** [vuejs/vitepress#1709] [Q&A] [answered]
I'm using the nav to navigate and don't need the sidebar, so I disabled the sidebar.

However, the main area rendering markdown is still narrow. Is there a way to config vitepress default theme and making content container wider?  

PS.  There are plenty of areas wasted on my Macbook screen on both right and left side. Please refer to below picture.

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/311397/208253282-fbbc147a-4073-44d1-a9f3-444c19e2ed51.png">

**Comment by xu4wang** [comment, marked as answer]
Digging into the code, there is hard coded max-width inside:

https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPDoc.vue

```vue
@media (min-width: 1440px) {
  .VPDoc:not(.has-sidebar) .content {
    max-width: 784px;
  }
  .VPDoc:not(.has-sidebar) .container {
    max-width: 1104px;
  }
}
```
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/311397/208253750-d4e01f41-8f8e-4375-894d-a7fffe2a4cf4.png">

Is there an easy way I can override the two max-width?  thanks..

**Reply by brc-dd** [reply]
Just increase the specificity of your selectors or use `! important`, your CSS will override ours.

**Reply by xu4wang** [reply]
Sorry for the silly question.. I am not familiar with front end. 

how to increase?

Shall I create a css file under /doc and import it in nuxt.config.is?

**Reply by brc-dd** [reply]
This is not Nuxt 😅. Refer this: https://vitepress.vuejs.org/guide/theme-introduction#customizing-css and add some CSS like:

```css
/* .vitepress/theme/custom.css */
@media (min-width: 1440px) {
  .VPDoc:not(.has-sidebar) .content {
    max-width: 784px !important; /* <-- update your values */
  }
  .VPDoc:not(.has-sidebar) .container {
    max-width: 1104px !important;
  }
}
```

Also, might wanna give this a read: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#tips_for_handling_specificity_headaches

**Reply by xu4wang** [reply]
> This is not Nuxt 😅. Refer this: https://vitepress.vuejs.org/guide/theme-introduction#customizing-css and add some CSS like:
> 
> ```css
> /* .vitepress/theme/custom.css */
> @media (min-width: 1440px) {
>   .VPDoc:not(.has-sidebar) .content {
>     max-width: 784px !important; /* <-- update your values */
>   }
>   .VPDoc:not(.has-sidebar) .container {
>     max-width: 1104px !important;
>   }
> }
> ```
> 
> Also, might wanna give this a read: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#tips_for_handling_specificity_headaches

Thanks for the guide.. it's working.  below is the numbers I use now.  @brc-dd 

```css
/* .vitepress/theme/custom.css */

@media (min-width: 1440px) {

    .VPDoc:not(.has-sidebar) .content {
  
      max-width: 1284px !important; /* <-- update your values */
  
    }
  
    .VPDoc:not(.has-sidebar) .container {
  
      max-width: 1604px !important;
  
    }
    .VPDoc.has-aside .content-container {
        max-width: 1188px !important;
    }
  
  }
```
