### DISCUSSION TITLE
How to pass some data from config in Frontmatter?

### DISCUSSION THREAD

**Discussion by cawa-93** [vuejs/vitepress#1848] [Q&A]
VitePress offers several built in API to let you access app data. Like `useData` give you access to site data inside component. But how to get access to same data in Frontmatter section? It would be nice to somehow link view to site config. An imaginary example:

```yaml
layout: home

title: ${ useData().title }

hero:
  name: ${ useData().title }
  text: ${ useData().description }
```
