### DISCUSSION TITLE
Separate Logo for Dark and Light Mode

### DISCUSSION THREAD

**Discussion by abishekrsrikaanth** [vuejs/vitepress#2113] [Q&A]
Is it possible to have separate logos for dark and light mode?

**Comment by brc-dd** [comment]
https://vitepress.dev/reference/default-theme-config#logo

or https://vitepress.dev/reference/default-theme-home-page#hero-section if you meant logo in hero section:

```yaml
  image:
    light: /dark-logo.svg
    dark: /light-logo.svg
    alt: description
```
