### DISCUSSION TITLE
change copy icon

### DISCUSSION THREAD

**Discussion by lazarusA** [vuejs/vitepress#2901] [Q&A]
Hi,
how and where one could change the copy/paste icon visible in code blocks?

**Comment by brc-dd** [comment]
You can modify them from css like this:

```css
:root {
  --vp-icon-copy: url("data:image/svg+xml...");
  --vp-icon-copied: url("data:image/svg+xml...");
}
```

https://vitepress.dev/guide/extending-default-theme#customizing-css
