### DISCUSSION TITLE
Why does it load SVG's as `img`?

### DISCUSSION THREAD

**Discussion by babakfp** [vuejs/vitepress#3297] [Q&A]
Hi

When I use these:

```
layout: home
hero:
    image:
        light:
            src: /logo-light.svg
            alt: Vite
        dark:
            src: /logo-dark.svg
            alt: Vite
```

```
export default defineConfig({
        logo: { light: "/logo-light.svg", dark: "/logo-dark.svg", alt: "Zod" },
```

It renders them as `img` tags! How can I render them as SVG tags? The reason that I want this is to control the colors of the SVG with CSS.
