### DISCUSSION TITLE
about full srcreen config

### DISCUSSION THREAD

**Discussion by xxholly32** [vuejs/vitepress#3325] [Ideas]
To change the page to full screen, I need to introduce this configuration

```
:root {
    --vp-layout-max-width: 1920px;
}

.VPDoc.has-aside .content-container {
  max-width: 100% !important;
}
```

I wonder why the max-width of [ .content-container is 688px,](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPDoc.vue#L203) should it not be controlled by the outer container or add css var

Or if there's a better way to write it

**Comment by kaisugi** [comment]
I had the same issue, but managed to solve it

First setup your [custom css](https://vitepress.dev/guide/extending-default-theme#customizing-css), and then add some codes like this:

```css
:root {
  --vp-layout-max-width: 1920px;
}

.VPDoc:not(.has-sidebar) .container {
  max-width: 1584px !important;
}

.VPDoc:not(.has-sidebar) .content {
  max-width: 1264px !important;
}

.VPDoc.has-aside .content-container {
  max-width: 1168px !important;
}
```

[My website](https://llm-jp.github.io/awesome-japanese-llm/en/) is successfully modified over 688px using this technique
