### DISCUSSION TITLE
Create Custom Badge Type

### DISCUSSION THREAD

**Discussion by Karlstens** [vuejs/vitepress#3338] [Q&A]
Further to VitePress badge types "tip, info, warning, danger", how do we define our own badge types with their own colors, properties and borders?

https://vitepress.dev/reference/default-theme-badge

The VitePress guide details how to customize the existing stock badge types, but not how to create other badge types to compliment them.

**Comment by sharpchen** [comment]
You can find the `VPBadge` component in `node_modules\vitepress\dist\client\theme-default\components\VPBadge.vue`, you can see how it was implemented.
You may try customizing style for custom types for `VPBadge` in `custom.css`, if you ignore the type checking for badge type.

```css
/* custom.css */
.VPBadge.my-badge-type {
  border-color: var(--vp-badge-info-border);
  color: var(--vp-badge-info-text);
  background-color: var(--vp-badge-info-bg);
}
```
