### DISCUSSION TITLE
Is it possible to change ``title`` attribute content of copy button of code blocks?

### DISCUSSION THREAD

**Discussion by otabekoff** [vuejs/vitepress#3505] [Q&A]
I mean, I am now able to change the "copied" text into my language. https://github.com/vuejs/vitepress/issues/2828
I first tried with this method:
```css
html[lang="foo"] button.copied::before {
  content: "bar" !important;
  left: -5ch !important;
  width: calc(5ch - 1px) !important;
}
```
and then tried and stayed at this https://github.com/vuejs/vitepress/pull/2833:
```css
html[lang="es"] {
  --vp-code-copy-copied-text-content: 'Copiado'
}

html[lang="fr"] {
  --vp-code-copy-copied-text-content: 'Copié'
}
```

BUT, What about If I want to change the hover title text? It is now "Copy Code". I want to change that!
