### DISCUSSION TITLE
Using different images in dark and light theme

### DISCUSSION THREAD

**Discussion by jarinox** [vuejs/vitepress#3560] [General]
Is it possible to display images (other than the logo) based on whether light or dark theme is active? I want to showcase different screenshots of my app when in dark or light theme as my app also supports dark and light themes.

**Comment by brc-dd** [comment]
Dark mode is basically `dark` class on `<html>`. So you can add some CSS like this (https://vitepress.dev/guide/extending-default-theme#customizing-css):

```css
html.dark .light-only {
  display: none !important;
}

html:not(.dark) .dark-only {
  display: none !important;
}
```

Then just add classes to your image elements:

```html
<img class="dark-only" src="/dark-mode-image" ... />
<img class="light-only" src="/light-mode-image" ... />
```

In markdown you can either keep using img tag or you can also do:

```md
![alt](/dark-mode-image){.dark-only}
![alt](/light-mode-image){.light-only}
```
