### DISCUSSION TITLE
Is .nojekyll file necessary when deploying via GitHub Action?

### DISCUSSION THREAD

**Discussion by pavelhoral** [vuejs/vitepress#3629] [General]
I am setting up simple page for my personal project and was kind of surprised by the presence of `touch docs/.vitepress/dist/.nojekyll`  introduced in https://github.com/vuejs/vitepress/commit/908084fbe992eed4e7bbda760aabeb38f243c268.

Is this really necessary? I thought that by using GitHub Actions one can bypass the Jekyll build step and upload raw files to be deployed. This seems to be also suggested by the GitHub interface where you can automatically setup Jekyll based build which generates workflow file with the following contents:

```
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
```

I will create a quick test, but I think this `touch ... .nojekyll` is unnecessary and a bit confusing.
