### DISCUSSION TITLE
Option to invert nav logo on dark mode

### DISCUSSION THREAD

**Discussion by pandermatt** [vuejs/vitepress#3659] [Ideas]
Hey, I used VitePress in some projects already, and I noticed that every logo i used looks bad on dark mode.
I think this might be also the issue for others and instead of having two different icons (light and dark)
it would maybe be preferable to auto invert the icon with `filter: grayscale(1) invert(1);`

![image](https://github.com/vuejs/vitepress/assets/20790833/caee46e6-5fe6-4519-8d67-405ba9025261)

I was thinking about adding `logoInverted` (or `silhouetteLogoInDark`) `themeConfig` and then in `VPNavBarTitle.vue`

```html
<VPImage v-if="theme.logo" class="logo" :image="theme.logo" :class="{ inverted: theme.logoInverted }" />
```

with the class

```css
.dark .logo.inverted {
  filter: brightness(0) invert(1);
  # or (both have the same effect)
  filter: grayscale(1) invert(1);
}
```

If this idea does not fit the project, the workaround would be to use following in `styles.css`
```css
.dark .VPImage.logo {
  filter: brightness(0) invert(1);
}
```

**Comment by pandermatt** [comment]
Something similar is already in `vp-sponsor.css`

```css
.dark .vp-sponsor-grid-image {
  filter: grayscale(1) invert(1);
}
```
