### DISCUSSION TITLE
How to make Hero's buttons bigger?

### DISCUSSION THREAD

**Discussion by linusang-spark** [vuejs/vitepress#3936] [Q&A] [answered]
Is there a quick way to make the buttons bigger? or do I have to create a custom Home Page to do that?

**Comment by brc-dd** [comment, marked as answer]
add css: https://vitepress.dev/guide/extending-default-theme#customizing-css

```css
.VPHero .VPButton {
    padding: 20px 50px !important;
}
```
