### DISCUSSION TITLE
Custom fonts do not take effect ?

### DISCUSSION THREAD

**Discussion by UnspokenSpell** [vuejs/vitepress#4314] [Q&A] [answered]
My goal: to use a different font.

To do this, I made the following changes:
```js
// /theme/index.js
import DefaultTheme from 'vitepress/theme-without-fonts'
import './myfont.css'
export default DefaultTheme
```

```css
/* /theme/myfont.css */
@import url("https://cdn.jsdelivr.net/gh/CMBill/lxgw-wenkai-web/style.css");
:root {
  --vp-font-family-base: "LXGW WenKai";
  --vp-font-family-mono: "LXGW WenKai Mono", monospace;
}
```
The structure of my project \
![2024-10-28_12-06-48](https://github.com/user-attachments/assets/9c8418e2-7f07-4162-9458-ed7731caff21)

I tried to use local files, but it didn't work. After changing the path several times, I tried Google and browsed many articles. After seeing [issue_3864], I used online resources to avoid path problems.
After trying various things, I still **couldn't** get the custom font to work.

**Does anyone know how to do this?🙏**

> VitePress: v1.4.1 \
> Language: zh-CN(or Chinese Simple)

[issue_3864]: https://github.com/vuejs/vitepress/issues/3864
