### DISCUSSION TITLE
Is it possible to install and run vitepress completely within Github action for a repo that does not use node otherwise?

### DISCUSSION THREAD

**Discussion by yorkshire-pudding** [vuejs/vitepress#4362] [Q&A] [answered]
I have a few repos and wondering about using Vitepress to build Github Pages for the docs rather than using the wiki.  The repos are for PHP based tools and modules for Backdrop CMS so don't normally use `node` so don't have the local build step.

Is it possible to build it into the github action so node and vitepress are installed and the docs are build into pages without any local node steps?  The docs would be in `.md` format.

**Comment by brc-dd** [comment, marked as answer]
You can install vitepress on CI too, but might need to lock its version in workflow if you don't want a package.json in your repo.

Some steps like this maybe:

```sh
cd docs
npm add vitepress@1.5.0
npx vitepress build
```

You'll need to store the config file in your repo too (`docs/.vitepress/config.mjs`). Autocompletions inside that won't work if you're editing it locally and don't have node install.

**Reply by yorkshire-pudding** [reply]
Thank you @brc-dd - this got me most of the way there.

I found that I could get latest by doing `npm install vitepress` and by removing the cache definition from "Setup node".  In case it helps others, this is what I ended up with:

<details>
<summary>deploy.yml</summary>

```yaml
# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy VitePress site to Pages

on:
  # Runs on pushes targeting the `main` branch. Change this to `master` if you're
  # using the `master` branch as the default branch.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install VitePress and build pages
        run: |
          cd docs
          npm install vitepress
          npx vitepress build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

</details>
