### DISCUSSION TITLE
background-image

### DISCUSSION THREAD

**Discussion by MikeCZ23** [vuejs/vitepress#4370] [Q&A]
I want a background-image but the image is stuck
![Snímek obrazovky 2024-11-20 135124](https://github.com/user-attachments/assets/8488f456-d48c-499e-878b-f811bca01c2a)

```css
body::after {
  content: "";
  background: url(https://img.freepik.com/free-photo/christmas-ornaments-candy-canes-dark-background_24972-620.jpg);
  background-size: cover; 
  background-repeat: repeat;
  background-attachment: fixed;
  background-position: center top;
  margin: 0;
  padding: 0;
  opacity: 0.5;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  position: absolute;
  z-index: -1;   
}
```
