### DISCUSSION TITLE
Burger (nav) not working on *some* mobile devices

### DISCUSSION THREAD

**Discussion by szarkans** [vuejs/vitepress#4381] [Q&A]
Don't really know what the issue here. Some IPhone users and some Android users can open mobile navbar, but some are not, even tho it still there. Only fix i could do - show navbar on top of a page with some CSS tweaks.

<https://wiki.catcraftmc.ru>

Video - Firefox and Edge
https://github.com/user-attachments/assets/6c08a533-88e2-481a-b99e-eeda1f90f96e

**Comment by szarkans** [comment]
This kinda fixes it, but i'm not sure if this right.
```css
VPNavScreen[data-v-2dd6d0c7] {
  position: relative; /* was `fixed` */
}
```
