### DISCUSSION TITLE
## h2标题自动加上了水平线，这个怎么出去？

### DISCUSSION THREAD

**Discussion by heliteng** [vuejs/vitepress#4387] [Q&A]
## h2标题自动加上了水平线，这个怎么移除？

**Comment by brc-dd** [comment]
Add this CSS:

```css
.vp-doc h2 {
  margin-top: 16px !important;
  border-top: none !important;
}
```

https://vitepress.dev/guide/extending-default-theme#customizing-css
