### DISCUSSION TITLE
VPDocAside.vue component in layout: docs

### DISCUSSION THREAD

**Discussion by erondpowell** [vuejs/vitepress#834] [Q&A]
I noticed that carbon Ads can be enabled/disabled in `config.js`.
Curious to know if there are plans to make  `VPDocAside.vue` optional as well.

**Comment by brc-dd** [comment]
```css
.aside {
  display: none !important;
}
```
