### DISCUSSION TITLE
How can I wrap text into two line by CSS?

### DISCUSSION THREAD

**Discussion by gyhyfj** [vuejs/vitepress#907] [Q&A] [answered]
These code doesn't work in component.

```css
.title {
  width: 100px;
  height: 50px;
  overflow: hidden; 
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
```
