### ISSUE TITLE
brand image overlaps with text in home layout

### ISSUE THREAD

**Issue by MarkusKeck** [vuejs/vitepress#1088]
### Describe the bug

If you have a home layout with a long text and a brand image they will overlap

### Reproduction

```yml
---
layout: home

hero:
    name: Test
    text: Long text goes here
    tagline: Something
#    image:
#        light: /assets/test1.svg
#        dark: /assets/test2.svg
#        alt: test
---
```

### Expected behavior

Image and text should not overlap

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 110.74 GB / 127.91 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)    
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
