### ISSUE TITLE
Github pages shows index.md natively

### ISSUE THREAD

**Issue by sangyoo91** [vuejs/vitepress#1144]
### Describe the bug

I have `.github/workflows/deploy.yml` set up in my project root as doc instructed. And Github action succeeds. However, when I visit my pages, its not vitepress that I see but regular github pages.

Is there some settings I have to alter in github repository itself?

### Reproduction

This is my app structure 

```
- root
  - docs (vitepress)
    - theme/index.js
    - config.js
    - index.md 
  - src (src for my vue component lib)
  - dist (for my vue component lib)
```

This is my github workflow deploy.yml
```
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci

      - name: Build
        run: npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
```

### Expected behavior

Built vitepress in github pages.

### System Info

```shell
(Local)
System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 99.72 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
```

### Additional context

My repository is in an organization.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
