### ISSUE TITLE
Style error when custom max-width

### ISSUE THREAD

**Issue by songispm** [vuejs/vitepress#1147]
### Describe the bug

<img width="606" alt="image" src="https://user-images.githubusercontent.com/38745323/183691344-07a0abfb-b01a-4d79-86c8-1b22fb5fc957.png">

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/38745323/183691940-a9caf108-f3d1-4569-8f77-4c1486ee4fa4.png">

### Reproduction

When I custom the max-width use --vp-layout-max-width: 1680px;

Then style of sidebar is ugly when I resize the window.

### Expected behavior

The title of the header and the sidebar are always aligned.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.91 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 101.0
    Safari: 15.5
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Can you share a reproducible example? Doesn't seem to cause any such issue for me.

**Comment by songispm** [comment]
> Can you share a reproducible example? Changing `--vp-layout-max-width` doesn't seem to cause any such issue for me.
![2022-08-11_11-48-54 (1)](https://user-images.githubusercontent.com/38745323/184062125-866212ee-f05d-4faa-978f-b25129e7ed84.gif)

**Comment by yzqdev** [comment]
Cause many style don't use css varibles, instead use accurate numbers like ` max-width: 688px;` Sometimes we have to use `!important` to override it,here is my style;
```css
:root {
    --vp-layout-max-width: 95%;
    --vp-sidebar-width: 15rem;
    --vp-nav-height-desktop:50px;
}
.content-container {
    max-width: 100% !important;
}
.container {
    max-width: var(--vp-layout-max-width) !important;
}
```
