### ISSUE TITLE
In home layout the hero.image.src attribute is not translated  

### ISSUE THREAD

**Issue by crguezl** [vuejs/vitepress#1326]
### Describe the bug

I have the following `index.md` home page:

```yml
---
layout: home
hero:
  name: DMSI
  text: DESARROLLO Y MANTENIMIENTO DE SISTEMAS DE INFORMACIÓN
  tagline: Curso 22/23
  image:
    src: /assets/images/logo-ull.png
    alt: DMSI
  actions:
    - theme: brand
      text: Get Started
      link: /temas/tema0-presentacion/
    - theme: alt
      text: View on GitHub
      link: https://github.com/ULL-ESIT-DMSI/vitepress-getting-started
features:
  - icon: ⚡️
    title: Vite, The DX that can't be beat
    details: Lorem ipsum...
  - icon: 🖖
    title: Power of Vue meets Markdown
    details: Lorem ipsum...
  - icon: 🛠️
    title: Simple and minimal, always
    details: Lorem ipsum...
---
```

Though the logo image specified in `hero.image.src` is there:

```
 docs git:(main) git ls-files assets/images 
assets/images/logo-ull.png
```

and the `yarn docs:dev` visualizes the image correctly, when I do a `docs:build` followed by a `docs:serve`  the image is not found:

<img width="1081" alt="Captura de Pantalla 2022-09-12 a las 13 57 44" src="https://user-images.githubusercontent.com/1142554/189660241-a1211eec-a805-4a65-866c-747375488a9d.png">

The repo is here [ULL-ESIT-DMSI/vitepress-getting-started](
https://github.com/ULL-ESIT-DMSI/vitepress-getting-started/tree/1f0a5905f6a0fec9da28ec94c888b41e8a0945a3) at commit `1f0a5905f6a0fec9da28ec94c888b41e8a0945a3`

### Reproduction

Clone the repo 

 [ULL-ESIT-DMSI/vitepress-getting-started](
https://github.com/ULL-ESIT-DMSI/vitepress-getting-started/tree/1f0a5905f6a0fec9da28ec94c888b41e8a0945a3) at commit `1f0a5905f6a0fec9da28ec94c888b41e8a0945a3`

### Expected behavior

Expect the image to be found at built time

### System Info

```shell
✗ npx envinfo --system --npmPackages vitepress --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 15.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.0.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Edge: 105.0.1343.33
    Firefox: 103.0.1
    Safari: 15.6.1
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
