### ISSUE TITLE
Add Video / 2nd Hero Image to Home Layout

### ISSUE THREAD

**Issue by karlhorky** [vuejs/vitepress#1340]
### Is your feature request related to a problem? Please describe.

Currently, the `home` layout only allows for a single image, which may not be enough for some projects (eg. https://www.safeql.dev/ ), who may want to have one large image and then also a video of the product, both in the upper hero section of the page.

### Describe the solution you'd like

It would be nice to have a more customizable / flexible way to output arbitrary (html or markdown) content, eg what I tried with the `tagline` here:

```yaml
---
layout: home

hero:
  name: SafeQL
  text: Write SQL Queries With Confidence
  tagline: SafeQL is an ESLint plugin for writing SQL queries in a type-safe way.<br><br><video src="...">
```

### Describe alternatives you've considered

If that's not an option, then having another configuration option like `image2` would be an alternative.

Another alternative that I considered (but could not figure out) would be to somehow be able to extend **ONLY** this single section of that particular template, similar to what is being talked about here:

- https://github.com/vuejs/vitepress/issues/235
- https://github.com/vuejs/vitepress/issues/235#issuecomment-1178642033

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We can just provide a slot (#1062) with default content being the image. Users can then customize it to add video, etc.?

**Comment by kiaking** [comment]
Yes! For the customized image, I think that works. Video embedding I meant was, it would be cool if we can do this in frontmatter.

```yml
---
layout: home
video: https://youtube-url.com/...
---
```

And then the default theme will handle it and create beautiful looking component. Like it has Thumbnail and play button, and when user clicks it, it opens modal and make video decent amount of size and such 👀 

But as you mentioned I think we can start from #1062 and I think it should cover many usecases 👍
