### ISSUE TITLE
make properties of hero optional

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1435]
Suppose someone just wants tagline not the text. Currently, in these cases, Vue runtime gives warnings.

```yaml
---
layout: home

hero:
  name: foo
  tagline: bar
---
```
