### ISSUE TITLE
allow specifying common alt for logo

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#1436]
Currently one needs to do this:

```yaml
---
layout: home
hero:
  image:
    light:
      src: /light.svg
      alt: logo
    dark:
      src: /dark.svg
      alt: logo
---
```

This can be simplified to:

```yaml
---
layout: home
hero:
  image:
    light: /light.svg
    dark: /dark.svg
    alt: logo
---
```
