### ISSUE TITLE
outline显示异常

### ISSUE THREAD

**Issue by zstu0210** [vuejs/vitepress#1464]
### Describe the bug

当没有sidebar，有footer和outline时，滚动轴在底部，outline将会显示异常

### Reproduction

![image](https://user-images.githubusercontent.com/91824770/195075167-b993e607-7af0-4e63-88f0-1ba17569a307.png)

### Expected behavior

修复outline显示异常，固定在原位不动

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 8.82 GB / 15.69 GB
  Binaries:
    Node: 16.17.0 - D:\developer_tools\nodejs\node.EXE
    npm: 8.19.1 - D:\developer_tools\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0)
    Internet Explorer: 11.0.22000.120
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This is not exactly a bug. We are using backdrop filter on navbar so that's kind of expected. For now consider adding some custom css like:

```css
.VPNav {
  background: rgba(255,255,255) !important;
  backdrop-filter: none !important;
  -webkit-backdrop-filter: none !important;
}

.dark .VPNav {
  background: rgba(36,36,36) !important;
}
```
