### ISSUE TITLE
Support svg images in the features section in home layout

### ISSUE THREAD

**Issue by MarkusKeck** [vuejs/vitepress#1702]
### Is your feature request related to a problem? Please describe.

Currently only emojis are supported in the features section in home layout, which is already great, but there are a lot of cases where a custom image would be a better fit.

Open discussion
https://github.com/vuejs/vitepress/discussions/1589#discussioncomment-4415494

### Describe the solution you'd like

```
 features:
  - icon: [LINK TO SVG IMAGE]
    title: my title
    details: my details
    link: https://github.com/vuejs/vitepress
    linkText: Let's jump right in
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
