### ISSUE TITLE
How to add linefeed/linebreak in details of Home layout

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#1809]
### Is your feature request related to a problem? Please describe.

```yaml
---
layout: home

features:
  - icon: 🛠️
    title: Simple and minimal, always
    details: Lorem ipsum...
  - icon:
      src: /cool-feature-icon.svg
    title: Another cool feature
    details: Lorem ipsum...
  - icon:
      dark: /dark-feature-icon.svg
      light: /light-feature-icon.svg
    title: Another cool feature
    details: Lorem ipsum...
---

```
I want to know how to add line break in details.

What I have tried:
```
---yaml
details: Lorem <br />ipsum...
---
```
It doesn't work.

Then try:
```
---yaml
details: Lorem&#13,ipsum...
---
```
It doesn't work.

Then:
```yaml
details: |
  Lorem
  ipsum...
```
It doesn't work, too.

Then I tried JSON. The document says that Json also works.
> VitePress also supports JSON frontmatter syntax, starting and ending in curly braces:

```JSON
---
{
  "details": "Lorem\nipsum..."
}
```
---
It doesn't work, too.

### Describe the solution you'd like

I want to know how to achive it.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
That last one should work (using `|`), but we don't respect whitespace on .details, so just add something like this to CSS for now, it'll work:

```css
.VPFeature .details {
  white-space: pre;
}
```

**Comment by you-hengh** [comment]
Maybe... #1913

**Comment by arcqiufeng** [comment]
> Maybe... #1913

Thank you for your PR.

所以更新到最新版本后，是用加“\n"的方式吗？

**Comment by you-hengh** [comment]
> > Maybe... #1913
> 
> Thank you for your PR.
> 
> 所以更新到最新版本后，是用加“\n"的方式吗？

你可以这样使用:
### 方法一 `<br/>`
```yml
features:
  - icon: 🧑‍🎓
    title: 如果善于提问<br/>你会厉害很多
    details: ''
    linkText: 阅读全文
    link: /article/blog/悟道/如果善于提问，你会厉害很多
```
### 方法二 `<pre>`
```yml
features:
  - icon: 🧑‍🎓
    title: "<pre>如果善于提问<\n>你会厉害很多</pre>"
    details: ''
    linkText: 阅读全文
    link: /article/blog/悟道/如果善于提问，你会厉害很多
```
**注意方法二中的 title 需要携带引号(网页中不会展示引号)**
