### ISSUE TITLE
Bad contrast for Custom Containers on light theme

### ISSUE THREAD

**Issue by sergejcodes** [vuejs/vitepress#1824]
### Describe the bug

Since the the theme update in [1.0.0-alpha.37](https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md#100-alpha37-2023-01-17) the text to background contrast ration of [Custom Containers](https://vitepress.vuejs.org/guide/markdown#custom-containers) got worse. The text became much more difficult to read.

Here's a side-by-side comparison image:

![comparison](https://user-images.githubusercontent.com/68379148/213670149-9f041ec9-f9b9-4e77-8983-0360f43f240f.jpg)

### Reproduction

1. Go to https://vitepress.vuejs.org/guide/markdown#custom-containers
2. Switch to light theme

### Expected behavior

`--vp-custom-block-*-text` variables on light theme should be either set to `--vp-c-*-dark` or `--vp-c-*-darker` instead of `--vp-c-*`.

For Example: 

```css
:root {
  --vp-custom-block-warning-text: var(--vp-c-yellow-darker);
}

.custom-block.warning {
    color: var(--vp-custom-block-warning-text);
}
```

### System Info

```shell
-
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
