### ISSUE TITLE
SVG icons in `feature` elements do not respect their size setting

### ISSUE THREAD

**Issue by dhazel** [vuejs/vitepress#1886]
### Describe the bug

# Bug
SVG feature icons in the `home` layout expand to fit the width of their feature element, rather than being constrained to the size specified in their `width` declaration.

### Reproduction

# Context
Given the frontmatter

```
---
layout: home

hero:
  name: Bug example

features:
  - icon:
      src: /flag-solid.svg
      width: 50
    title: Bug example
    details: The icon expands to fit the width of the feature element, rather than being constrained to 50px
---
```

### Expected behavior

# Expected
The feature icon is expected to size to the width specified by the `width` declaration.

### System Info

```shell
System:
    OS: Windows 10
  Binaries:
    Node: 18.13.0
    npm: 8.19.3
  Browsers:
    Chrome: 109
  npmPackages:
    vitepress: ^1.0.0-alpha.40 => 1.0.0-alpha.45
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
