### ISSUE TITLE
Return semi-transparent header background

### ISSUE THREAD

**Issue by Andrew-web-coder** [vuejs/vitepress#1897]
### Is your feature request related to a problem? Please describe.

I upgraded from alpha36 to the latest alpha and immediately noticed that it is missing on of the nicest touch of VitePress.

### Describe the solution you'd like

Please, return semi-transparent, blurry header background!

OR at least give an example of how to achieve the same effect, I tried but no luck.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Andrew-web-coder** [comment]
If anyone else is interested, I managed to bring it back with this ugly CSS code:

```css
.VPNavBar {
  backdrop-filter: blur(12px) !important;
  background-color: hsla(0, 0%, 100%, 0.85) !important;
}

.VPNavBar.has-sidebar {
  backdrop-filter: none !important;
  background: transparent !important;
}

.VPNavBar .content-body {
  background: transparent !important;
}

.VPNavBar.has-sidebar .content-body {
  backdrop-filter: blur(12px);
  background-color: hsla(0, 0%, 100%, 0.85) !important;
}

.VPNavBar.has-sidebar .curtain::before {
  background: transparent !important;
}

.VPNavBar.has-sidebar.fill .curtain::before {
  border-top: 1px solid var(--vp-c-gutter);
}
```
