### ISSUE TITLE
Make prev / next links changeable

### ISSUE THREAD

**Issue by MarkusKeck** [vuejs/vitepress#1914]
### Is your feature request related to a problem? Please describe.

Currently it is only possible to customize the text of the links, but not the link itself, this is taken from the sidebar. However, if a page does not exist in the sidebar, no prev / next link can be set or modified.

The current behavior causes the vitepress application to crash if the page is not in the sidebar and you set a prev link via frontmatter, because there is no prev link whose text you can change. As next link always the first page of the sidebar is used.

I think it would be good if you could customize not only the text but also the link.

![image](https://user-images.githubusercontent.com/19492739/217874237-392d2b8c-10e8-40da-8574-c21b9e56b9d5.png)

### Describe the solution you'd like

Change the frontmatter options from 

```yml
---
prev: 'Get Started | Markdown'
---
```

to

```yml
---
prev:
    text: 'Get Started | Markdown'
    link: '/gettingstarted/markdown'
---
```

### Additional context

```yml
// prev-next.d.ts
    prev: {
        text: any;
        link: string;
    };
    next: {
        text: any;
        link: string;
    };
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
