### ISSUE TITLE
[hero] : The localization problem of `image bg '

### ISSUE THREAD

**Issue by RSS1102** [vuejs/vitepress#2217]
### Describe the bug

When I tried to change the style of the `image` on the homepage, there were some situations where I encountered problems.
under Path: 
>  .vitepress\theme\styles\vars.css
```css
@keyframes logo-spin {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
}

.image-src {
  animation: logo-spin infinite 20s linear;
}
```

### Reproduction

stackblitz :  https://stackblitz.com/edit/vite-ib4s68?file=README.md

repo and explanation  : https://github.com/RSS1102/vite-ib4s68

### Expected behavior

On the mobile end
![image](https://user-images.githubusercontent.com/81673017/232112071-46a6571e-a032-4aba-a8e7-fbcf2c3f4c5c.png)

On the PC end
![image](https://user-images.githubusercontent.com/81673017/232112002-249e061f-bb8f-4dbc-8493-6d388feaf6fc.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 2.19 GB / 13.86 GB
  Binaries:
    Node: 18.12.1 - E:\node\node.EXE
    Yarn: 1.22.19 - E:\node\yarn.CMD
    npm: 9.4.2 - E:\node\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.64 => 1.0.0-alpha.64
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by RSS1102** [comment]
Actual display:
On the mobile end
![image](https://user-images.githubusercontent.com/81673017/232119244-1ba3c735-2eca-43d4-a1c0-afbb46613b79.png)

On the PC end
![image](https://user-images.githubusercontent.com/81673017/232119157-3b64f9bd-f1c5-481e-a2e8-cfff8e1d9aa9.png)

**Comment by brc-dd** [comment]
Apply the styles on the container itself:

```css
.image-container {
  animation: logo-spin infinite 20s linear;
}
```
