### ISSUE TITLE
Config 'base' option and hrm update not work.

### ISSUE THREAD

**Issue by wgf4242** [vuejs/vitepress#2348]
### Describe the bug

update index.md -> hero->actoins->text  `Markdown Examples` to `Markdown Examples1`, hrm update not work.
If remove 'base' option， hrm works.
Tested with `vitepress dev`.

index.md
```
---
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "My great project"
  text: "My great project"
#  tagline: My great project tagline
  actions:
    - theme: brand
      text: Markdown Examples
      link: /markdown-examples
    - theme: alt
      text: API Examples
      link: /api-examples
```

```
// package.json
{
  "devDependencies": {
    "vitepress": "1.0.0-alpha.75"
  },
  "scripts": {
    "docs:dev": "vitepress dev",
    "docs:build": "vitepress build",
    "docs:preview": "vitepress preview"
  }
}
```

### Reproduction

..

### Expected behavior

..

### System Info

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 36.42 GB / 47.93 GB
  Binaries:
    Node: 16.13.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - d:\wgf\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-alpha.75 => 1.0.0-alpha.75
```

### Additional context

config.ts
```
import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "My Awesome Project",
  description: "A VitePress Site",
  base: "/static/help",
  themeConfig: {
    https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    sidebar: [
      {
        text: 'Examples',
        items: [
          { text: 'Markdown Examples', link: '/markdown-examples' },
          { text: 'Runtime API Examples', link: '/api-examples' }
        ]
      }
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  }
})
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
