### ISSUE TITLE
How do you solve the problem of each page having the same last update timestamp when building and deploying your site？

### ISSUE THREAD

**Issue by shelley-xl** [vuejs/vitepress#2420]

**Comment by brc-dd** [comment]
How are you building/deploying it?

**Comment by brc-dd** [comment]
can you share your workflow, you probably need to update your actions/checkout script to include depth

**Comment by brc-dd** [comment]
Update the checkout part to this:

```yaml
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```
