### ISSUE TITLE
Question: How to disable inferred "Home" page title

### ISSUE THREAD

**Issue by lhsazevedo** [vuejs/vitepress#249]
Is it possible to disable the "Home" page title when using `home: true`? I trying to keep just the site title.

Related code:
https://github.com/vuejs/vitepress/blob/74f5adafcde8a597939fbb37422aa68187b6dad4/src/node/markdownToVue.ts#L129-L141

**Comment by ElMassimo** [comment]
Not in HTML, but in social previews, adding this to the frontmatter in `index.md`  should do the trick:

```yaml
head:
  - - meta
    - name: twitter:title
      content: My Site
  - - meta
    - name: og:title
    - content: My Site
```
