### ISSUE TITLE
Dark Mode out of the box

### ISSUE THREAD

**Issue by nico-bachner** [vuejs/vitepress#251]
**Is your feature request related to a problem? Please describe.**
Dark mode is becoming ever more popular, with a number of benefits such as less strain on the eyes, and less battery consumption.
Plus, it's cool.

It would be nice if VitePress would ship dark mode out of the box.

**Describe the solution you'd like**
It seems to me that dark mode would be quite simple to implement due to the existing architecture of the default theme. Since CSS Variables are used and are all found in [vars.css](https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/styles/vars.css), the most simple solution solution would likely to modify the value of the variables based on the user's preference.

Currently, this is what [vars.css](https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/styles/vars.css) looks like:

``` css
:root {

  --c-white: #ffffff;
  --c-black: #000000;

  ...

}
```

Using `prefers-color-scheme`, we could do the following:

``` css
@media (prefers-color-scheme: light) {
  :root {

    --c-white: #ffffff;
    --c-black: #000000;

    ...

  }
}
@media (prefers-color-scheme: dark) {
  :root {

    --c-white: #000000;
    --c-black: #ffffff;

    ...

  }
}
```

Of course, there are more subtleties to the change, such as dealing with shadows and such, all of which will have to adjusted to work for dark mode as well, but in general, I believe this approach should make the implementations relatively straightforward.

Another minor point that will need to be addressed is the naming convention for the variables. Since white becomes black in dark mode, it would probably be clearer if we renamed `--c-white` to something along the lines of `--c-background`.

**Describe alternatives you've considered**
I don't see any obvious alternatives, both in idea and implementation.

Of course, one could simply do away with dark mode, but we would be missing out on its benefits.

**Additional context**
N/A

**Comment by codemonkey800** [comment]
I was thinking the same thing too while reading the Vite docs 😆 

I wonder if this is something that could be implemented similarly to https://github.com/vuejs/vuepress/pull/2301.

The approach is mostly straightforward, but we have to keep in mind of some components not using colors from `vars.css`. A good example is the `BuySellAds.vue` component:
https://github.com/vuejs/vitepress/blob/9d6b8cadcc6cd59bde6b9b20037f9038190672ce/src/client/theme-default/components/BuySellAds.vue#L68-L71

**Comment by nico-bachner** [comment]
Yeah that would be something we would have to keep in mind. Could we enforce the abstraction of all colours in `vars.css`, or would this pose any problems down the road?
For the existing components, I guess we would have to manually check that all colours are declared in `vars.css`, and fix where that is not the case.

Unrelated question: how do you reference specific parts of a file the way you did in your comment? It looks like a cool feature.

**Comment by codemonkey800** [comment]
It would probably be a good idea to consolidate all of the colors into one location so that the light / dark themes can be modified easily. 

You can link specific lines by clicking on them 😄 
https://stackoverflow.com/a/31282559

**Comment by nico-bachner** [comment]
Agreed.

Thanks for the tip 👏🏼

**Comment by benatkin** [comment]
That looks like a nice way of implementing it.

It looks like there's some [colors here](https://github.com/vuejs/vitepress/blob/master/src/client/theme-default/styles/custom-blocks.css) that may need to be put into vars

For another vite example, [vitesse](https://github.com/antfu/vitesse) has dark mode built in, with [windicss](https://github.com/windicss/windicss) which is based on Tailwind, and it works pretty well.

**Comment by posva** [comment]
FYI @kiaking started working on some theme redesign and it includes dark mode too

**Comment by brc-dd** [comment]
Based on VuePress' [default dark mode vars](https://v2.vuepress.vuejs.org/reference/default-theme/styles.html#style-file), one can do this in their stylesheet  for now:

```scss
@media (prefers-color-scheme: dark) {
  *,
  ::before,
  ::after {
    // brand colors
    --c-brand: #3aa675;
    --c-brand-light: #349469;

    // background colors
    --c-bg: #22272e;
    --c-bg-light: #2b313a;
    --c-bg-lighter: #262c34;

    // text colors
    --c-text: #adbac7;
    --c-text-light: #96a7b7;
    --c-text-lighter: #8b9eb0;
    --c-text-lightest: #8094a8;

    // border colors
    --c-border: #3e4c5a;
    --c-border-dark: #34404c;

    // custom container colors
    --c-tip: #318a62;
    --c-warning: #ceab00;
    --c-warning-bg: #7e755b;
    --c-warning-title: #ceac03;
    --c-warning-text: #362e00;
    --c-danger: #940000;
    --c-danger-bg: #806161;
    --c-danger-title: #610000;
    --c-danger-text: #3a0000;
    --c-details-bg: #323843;

    // code blocks vars
    --code-hl-bg-color: #363b46;
  }

  // plugin-docsearch
  .DocSearch {
    --docsearch-logo-color: var(--c-text);
    --docsearch-modal-shadow: inset 1px 1px 0 0 #2c2e40, 0 3px 8px 0 #000309;
    --docsearch-key-shadow: inset 0 -2px 0 0 #282d55, inset 0 0 1px 1px #51577d,
      0 2px 2px 0 rgba(3, 4, 9, 0.3);
    --docsearch-key-gradient: linear-gradient(-225deg, #444950, #1c1e21);
    --docsearch-footer-shadow: inset 0 1px 0 0 rgba(73, 76, 106, 0.5),
      0 -4px 8px 0 rgba(0, 0, 0, 0.2);
  }
}
```
