### ISSUE TITLE
Markdown Page Title Parse Error

### ISSUE THREAD

**Issue by JesseEisen** [vuejs/vitepress#255]
**Describe the bug**  

When the page title is `21E08`. And after build, It will goes as `210000000`. It was treated as scientific notation number 

**To Reproduce**   

Set page frontmatter like next

```yaml
---
title: 21E08
subtitle: "xxxxx"
date: 2021-03-05
category: "xxx"
---
```

**Expected behavior**   

Expect the title will be treated as string not the number

**System Info**   
- vitepress v0.11.3
- vite v2.0.0-beta.30
- Node version: v15.4.0
- OS version: Big Sur 11.0.1 (20B29)
