### ISSUE TITLE
Code line numbers don't work well with text wrap

### ISSUE THREAD

**Issue by Jeff-Tian** [vuejs/vitepress#2567]
### Describe the bug

When allowing word wrap in code blocks, the line numbers don't work correctly.

### Reproduction

1. set the code block to allow text wrap:

```
    code {
        white-space: pre-wrap !important;
    }
```

2. set line numbers to true in config.ts
```
export default defineConfig({
  markdown: {    lineNumbers: true }
})
```

4. write a long line of code, you can see something like the following:

<img width="726" alt="image" src="https://github.com/vuejs/vitepress/assets/3367820/12fbabb1-7adf-40a9-a740-d73b57aef4d1">

### Expected behavior

The line number should not increment until a new line met

### System Info

```sh
System:
    OS: macOS 13.4.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 32.79 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.5.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Will be a bit difficult with the current line numbers implementation. You can workaround this by disabling the line numbers mode in your config and adding some css like this instead:

```css
code {
  white-space: pre-wrap !important;
  counter-reset: step;
  counter-increment: step 0;
  margin-left: 40px;
}

.line::before {
  content: counter(step);
  counter-increment: step;
  width: 2ch;
  margin-right: 36px;
  margin-left: calc(-36px - 2ch);
  display: inline-block;
  text-align: right;
  color: var(--vp-code-line-number-color);
}
```

Demo: https://stackblitz.com/edit/vite-bz9x8q?file=docs%2Findex.md
