### ISSUE TITLE
Configure the original theme color scheme

### ISSUE THREAD

**Issue by Charles7c** [vuejs/vitepress#2783]
### Describe the bug

Previously, I matched my document website with the color scheme of the original theme. Now that the new theme has been changed to purple, the overall look has become very unattractive. 

I have two options now: 
1. Do not upgrade,
2. Upgrade to fix other issues, but keep the color scheme unchanged.

### Reproduction

N/A

### Expected behavior

How to keep the color scheme unchanged while upgrading to the latest version?

### System Info

```sh
N/A
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
add this css

```css
:root {
  --vp-c-brand: var(--vp-c-green);
  --vp-c-brand-light: var(--vp-c-green-light);
  --vp-c-brand-lighter: var(--vp-c-green-lighter);
  --vp-c-brand-lightest: var(--vp-c-green-lightest);
  --vp-c-brand-dark: var(--vp-c-green-dark);
  --vp-c-brand-darker: var(--vp-c-green-darker);
  --vp-c-brand-darkest: var(--vp-c-green-darkest);
  --vp-c-brand-dimm-1: var(--vp-c-green-dimm-1);
  --vp-c-brand-dimm-2: var(--vp-c-green-dimm-2);
  --vp-c-brand-dimm-3: var(--vp-c-green-dimm-3);
}
```
```ts
// .vitepress/theme/index
import DefaultTheme from 'vitepress/theme'
import './styles.css'

// ...
```
