### ISSUE TITLE
Ability to add title to features section

### ISSUE THREAD

**Issue by itsWindows11** [vuejs/vitepress#2788]
### Is your feature request related to a problem? Please describe.

It would be good to be able to add title text to the features section.

### Describe the solution you'd like

Provide a property for setting the header text for features section.

Example:
```
---
layout: home
features-title: Features
features:
  - icon: 🛠️
    title: Simple and minimal, always
    details: Lorem ipsum...
  - icon:
      src: /cool-feature-icon.svg
    title: Another cool feature
    details: Lorem ipsum...
  - icon:
      dark: /dark-feature-icon.svg
      light: /light-feature-icon.svg
    title: Another cool feature
    details: Lorem ipsum...
---
```

### Describe alternatives you've considered

Using `::before` in CSS for the VPHomeFeatures element and setting `content` works but feels hacky and isn't accessibility friendly.

This is how it looks like with the workaround, basically what I'd want:

![image](https://github.com/vuejs/vitepress/assets/81253203/6b2d2506-6b08-445e-9937-662011645c35)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
