### ISSUE TITLE
Add ``codeCopyText`` feature into config.js to customize the text value of copy button of markdown code blocks.

### ISSUE THREAD

**Issue by otabekoff** [vuejs/vitepress#2828]
### Is your feature request related to a problem? Please describe.

I was making a documentation in another language other than English. And I'm translating it fully. But, I was unable to change the text of code copy button.

### Describe the solution you'd like

Adding this feature will be great for other too, by adding option for that in config.js>themeConfig. It may be ``codeCopyText`` for example.

### Describe alternatives you've considered

I've tried to use ``codeCopyText`` in config.js provided by ChatGPT. But, it didn't work as of its information database is limited until 2021-year.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Might be bit tricky, considering it's added via CSS. Something like this in your custom css might work:

```css
html[lang="foo"] button.copied::before {
  content: "bar" !important;
  left: -5ch !important;
  width: calc(5ch - 1px) !important;
}
```
