### ISSUE TITLE
Theme does not use header curtain on pages without sidebar

### ISSUE THREAD

**Issue by hschaefer123** [vuejs/vitepress#2864]
### Describe the bug

While scrolling long pages with disabled sidebar, the header shows just a border with the color of --vp-c-gutter.

Other pages with sidebar uses a curtain to smoothly soft the edge.

This inkonsistent usage of scrolling directly feels strange. Maybe not notices so far, because Vitepress site does not seem to have page without sidebar.

### Reproduction

Just use a long page and add the following frontmatter to it

---
aside: false
outline: false
---

and start scrolling

### Expected behavior

Scrolling should behave konsistent on sidebar less page

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 7.84 GB / 15.95 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.111
    Edge: Spartan (44.22621.2215.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-rc.8 => 1.0.0-rc.8
```

### Additional context

My current workaround inside custom.css:

These are the vp rules, but without ` .VPNavBar.has-sidebar` prefix.

```css
@media (min-width: 960px) {
/*  .VPNavBar.has-sidebar .curtain { */
  .VPNavBar .curtain {
      position: absolute;
      right: 0;
      bottom: -31px;
      /*width: calc(100% - var(--vp-sidebar-width));*/
      width: 100%;
      height: 32px;
  }
}
@media (min-width: 960px) {
/*  .VPNavBar.has-sidebar .curtain::before { */
  .VPNavBar .curtain::before {
    display: block;
    width: 100%;
    height: 32px;
    background: linear-gradient(var(--vp-c-bg), transparent 70%);
    content: "";
  }
}
```
Maybe the final solution simply can be to remove `.has-sidebar` from code.

Also the default 'hard' gutter of #000000 disturbs a little bit the harmonic design.

My workaround solution is to use

`--vp-c-gutter: transparent; `

since it is also used for the footer separation, and the visual separation is not nessassary for me.

Live example usage on 
[btp.udina.de](https://btp.udina.de/about.html)

Best regards
Holger

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
