### ISSUE TITLE
Can the right navigation be set to highlight

### ISSUE THREAD

**Issue by huohuoren4** [vuejs/vitepress#2899]
### Is your feature request related to a problem? Please describe.

the right navigation isn't set to highlight in light mode as left. The current highlight is not very obvious

![Snipaste_2023-09-03_12-54-52](https://github.com/vuejs/vitepress/assets/34331100/a4852853-818d-40e4-a519-a4e48483b3da)

### Describe the solution you'd like

the style is set to the same as left nav

![image](https://github.com/vuejs/vitepress/assets/34331100/dff64f07-73ee-4e90-9107-05d5d0df4e17)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by zonemeen** [comment]
The css can be overridden like this:

```ts
// .vitepress/theme/index.ts
import DefaultTheme from 'vitepress/theme'
import './custom.css'

export default { ...DefaultTheme }
```

```css
/* .vitepress/theme/custom.css */
.outline-link:hover,
.outline-link.active {
  color: var(--vp-c-brand-1) !important;
}
```
