### ISSUE TITLE
Dark/Light mode icon in Features not wrapped

### ISSUE THREAD

**Issue by Soitora** [vuejs/vitepress#2923]
### Describe the bug

When using a custom Dark/Light icon for Homepage Features, the icon is not in a wrapper.

![image](https://github.com/vuejs/vitepress/assets/10836780/3c69c4fd-2acb-4052-800e-1ed61569fc33)

### Reproduction

```yaml
  - title: Extensions
    details: Online and offline reading from over a thousand sources, including MangaDex.
    icon: {
      light: https://styles.redditmedia.com/t5_fljgj/styles/communityIcon_dodprbccfsy71.png?width=256&s=629bb77b210a1c8cf92337032d0540bbfdb19c40,
      dark: https://styles.redditmedia.com/t5_fljgj/styles/communityIcon_dodprbccfsy71.png?width=256&s=629bb77b210a1c8cf92337032d0540bbfdb19c40,
      alt: MangaDex Logo,
      height: 32,
      width: 32,
    }
    link: /extensions/
```

### Expected behavior

The icon should match the other icons

### System Info

```pwsh
❯ npx envinfo --system --npmPackages vitepress --binaries --browsers

  System:
    OS: Windows 10 10.0.23536
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 16.03 GB / 31.73 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.0 - C:\Program Files\WinGet\Links\pnpm.EXE
  Browsers:
    Edge: Spartan (44.23536.1000.0), Chromium (117.0.2045.21)
    Internet Explorer: 11.0.23536.1000
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
