### ISSUE TITLE
heroImage not added to dist on build

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/vitepress#301]
**Describe the bug**

When index page has a heroImage, it works in `vitepress dev docs` mode but it's not bundled as an asset with `vitepress build docs`.

**To Reproduce**

Create `docs/index.md`:

```md
---
home: true
heroImage: logo.jpg
heroAlt: Logo image
heroText: Test
tagline:
actionText: Info
actionLink: /info
---
```

add `docs/logo.jpg` and run `vitepress build docs`.

**Expected behavior**

`docs/logo.jpg` is bundled as a hashed file, something like `docs/.vitepress/dist/assets/logo.xxxxx.jpg`, and referenced accordingly.

**System Info**
- vitepress version: 0.13.2
- vite version: 2.3.3
- Node version: 16.0.0
- OS version: macOS 11.3.1

**Comment by soulsam480** [comment]
@IlyaSemenov Hii, you have to make the image path absolute. i.e.
assuming the image is in `public` folder:
```yaml
---
home: true
heroImage: /logo.jpg
heroAlt: Logo image
heroText: Test
tagline:
actionText: Info
actionLink: /info
---
```
