### ISSUE TITLE
Problems with function result display when using Vue

### ISSUE THREAD

**Issue by MrZhuA00** [vuejs/vitepress#3045]
### Describe the bug

when I used js-vue, I encountered a function return result error.

### Reproduction

![image](https://github.com/vuejs/vitepress/assets/102725920/2ec08455-e76b-4867-8c50-ecff53925980)

error result: return 3 & 4
![image](https://github.com/vuejs/vitepress/assets/102725920/c5a8fd00-df4c-434f-94e6-2a1425193d3f)

but when i use the copy btn, this result is true

### Expected behavior

return 1 & 2

![image](https://github.com/vuejs/vitepress/assets/102725920/813531f2-ab5d-4224-a6c2-f821514f4bda)

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 5.76 GB / 15.85 GB
  Binaries:
    Node: 16.17.0 - ~\AppData\Local\fnm_multishells\2812_1696337629626\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\fnm_multishells\2812_1696337629626\yarn.CMD
    npm: 8.15.0 - ~\AppData\Local\fnm_multishells\2812_1696337629626\npm.CMD   
    pnpm: 8.6.0 - E:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.47)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: 1.0.0-rc.20 => 1.0.0-rc.20
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
The code blocks are rendered twice. (once for dark mode, once for light mode). On light mode it probably will be showing 1, 2 there.

**Comment by brc-dd** [comment]
Currently no. #3006 will fix this behavior. In meantime, if you want, you can revert back to single theme for color blocks:

```ts
// .vitepress/config.ts
export default {
  markdown: {
    theme: 'github-dark'
  }
}
```

```css
/* https://vitepress.dev/guide/extending-default-theme#customizing-css */
:root {
  --vp-code-block-color: rgba(255, 255, 245, 0.86);
  --vp-code-block-bg: #161618;
  --vp-code-block-divider-color: #000000;

  --vp-code-lang-color: rgba(235, 235, 245, 0.38);

  --vp-code-line-highlight-color: #000000;
  --vp-code-line-number-color: rgba(235, 235, 245, 0.38);

  --vp-code-copy-code-border-color: rgba(82, 82, 89, 0.32);
  --vp-code-copy-code-bg: #252529;
  --vp-code-copy-code-hover-border-color: rgba(82, 82, 89, 0.32);
  --vp-code-copy-code-hover-bg: #323238;
  --vp-code-copy-code-active-text: rgba(255, 255, 245, 0.86);

  --vp-code-tab-text-color: rgba(235, 235, 245, 0.6);
  --vp-code-tab-hover-text-color: rgba(255, 255, 245, 0.86);
  --vp-code-tab-active-text-color: rgba(255, 255, 245, 0.86);
}
```
