### ISSUE TITLE
How to use light mode and dark mode images in markdown?

### ISSUE THREAD

**Issue by Theo-messi** [vuejs/vitepress#3146]
For example used in GitHub - readme.

```html
![GitHub-Mark](./images/GitHub-Mark.png#gh-light-mode-only)

![GitHub-Mark-Light](./images/GitHub-Mark-Light.png#gh-dark-mode-only)
```

**Comment by brc-dd** [comment]
You can [add some CSS](https://vitepress.dev/guide/extending-default-theme#customizing-css) like this to make it work:

```css
:root:not(.dark) img[src$="#only-dark"],
:root:not(.dark) img[src$="#gh-dark-mode-only"] {
  display: none;
}

:root:is(.dark) img[src$="#only-light"],
:root:is(.dark) img[src$="#gh-light-mode-only"] {
  display: none;
}
```
