### ISSUE TITLE
The Mono custom font is not valid.

### ISSUE THREAD

**Issue by yassine-zhang** [vuejs/vitepress#3231]
### Describe the bug

I used a custom font by overriding the root variables `--vp-font-family-base` and `--vp-font-family-mono`.
It worked before version ^1.0.0-rc.4, but today I updated version ^1.0.0-rc.29 with the command `npm install vitepress@1.0.0-rc.29` and the Mono font won't work.

### Reproduction

The following is a blog theme folder based on VitePress.
https://github.com/yassine-zhang/VitePress-Blog/tree/main/docs/.vitepress/theme

### Expected behavior

By definition, Mono's fonts should work

### System Info

```Text
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 375.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - /usr/local/bin/node
    npm: 9.7.2 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.0
  npmPackages:
    vitepress: ^1.0.0-rc.29 => 1.0.0-rc.29
```

## catalogue
The table of contents is as follows:
<img width="245" alt="image" src="https://github.com/vuejs/vitepress/assets/63432395/ae5a955f-ac69-4cad-9da8-78ecf78e2d66">

## code
> I followed`https://vitepress.dev/guide/extending-default-theme#using-different-fonts` in `Layout.vue`
### index.js
```js
import Layout from "./components/Layout.vue"
import ...;
import "./custom.css"

export default {
  Layout,
  enhanceApp({ app, router, siteData }) {
    // ...
  },
};

```

### custom.css
```css
@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@500&display=swap");
@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&display=swap');

/* ... */

:root {
  --vp-font-family-base: "Noto Sans SC", arial, sans-serif;
  --vp-font-family-mono: "Roboto Mono", monospace;

  /* ... */
}

```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
