### ISSUE TITLE
GitHub Actions fail to build site often

### ISSUE THREAD

**Issue by Ahwxorg** [vuejs/vitepress#3293]
### Describe the bug

Whenever I commit a change to my repo; [Linkbase](https://github.com/Ahwxorg/Linkbase), GitHub is supposed to build VitePress and put it on GitHub Pages, but it often fails, and shows just the title of the repo, like it's a simple GH Pages Jekyll site.

### Reproduction

1. Clone my repository
2. Commit a change
3. Push to GitHub repo with Actions/Workflows enabled
4. See it not building sometimes

### Expected behavior

VitePress builds the site.

### System Info

```Text
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 173.63 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 17.0
  npmPackages:
    vitepress: ^1.0.0-rc.10 => 1.0.0-rc.20
```

### Additional context

Running `yarn vitepress build` locally does not display anything wrong.
<img width="336" alt="image" src="https://github.com/vuejs/vitepress/assets/87855602/33757f2d-6a2c-4f7c-8210-03feed3b962d">

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Microdeep-ZL** [comment]
I looked at your `.github/workflows/deploy.yml`. It was probably adapted from the sample script on [VitePress documentation](https://vitepress.dev/guide/deploy#github-pages). However, I think the sample script was wrong. If you specify multiple jobs (build and deploy), they will run on two independent runners. A runner is something like a container. 
You have `.vitepress/dist` in runner build, but you can't access it in runner deploy because they are two different containers.

The solution is to combine the two jobs into one.  I believe it will work. 
```
# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy VitePress site to Pages

on:
  # Runs on pushes targeting the `main` branch. Change this to `master` if you're
  # using the `master` branch as the default branch.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      # - uses: pnpm/action-setup@v2 # Uncomment this if you're using pnpm
      # - uses: oven-sh/setup-bun@v1 # Uncomment this if you're using Bun
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn # or pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: yarn install # or pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: |
          yarn vitepress build # or pnpm docs:build / yarn docs:build / bun run docs:build
          touch .vitepress/dist/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .vitepress/dist

  # # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
