### ISSUE TITLE
How to use 黑体 in vitepress and how to set it up?

### ISSUE THREAD

**Issue by Theo-messi** [vuejs/vitepress#3329]
### Is your feature request related to a problem? Please describe.

How to use “黑体” in vitepress and how to set it up?

### Describe the solution you'd like

Change text to “黑体”

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by sharpchen** [comment]
`--vp-font-family-mono` for code blocks in markdown, `--vp-font-family-base` for regular.
You can override them in `custom.css`
```css

/* custom.css */

:root {
  --vp-font-family-mono: ui-monospace, SFMono-Regular, 'SF Mono', 'Cascadia Code', Menlo, 'JetBrains Mono', Monaco,
    Consolas, 'Liberation Mono', 'Courier New', monospace;
  --vp-font-family-base: Roboto, 'Chinese Quotes', 'Inter var', 'Inter', ui-sans-serif,
    system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
    'Helvetica Neue', Helvetica, Arial, 'Noto Sans', sans-serif,
    'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
}
```

- https://vitepress.dev/guide/extending-default-theme#customizing-css
