### ISSUE TITLE
Modify the top navigation bar to be transparent or frosted translucent

### ISSUE THREAD

**Issue by Theo-messi** [vuejs/vitepress#3342]
### Is your feature request related to a problem? Please describe.

I want to set the navigation bar to be frosted or translucent. What should I do?

### Describe the solution you'd like

I want to set the navigation bar to be frosted or translucent. What should I do?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by xiaofan57** [comment]
I've used this CSS before, but it doesn't perform very well in some cases

```css
:root {
  --vp-nav-bg-color: transparent;
}

.VPNav,
.VPLocalNav {
  position: relative;
  background: var(--vp-nav-bg-color) !important;
}

.VPNav::after,
.VPLocalNav.reached-top::after {
  position: absolute;
  content: '';
  top: -1px;
  left: 0;
  right: 0;
  bottom: 0;
  backdrop-filter: saturate(180%) blur(12px);
  z-index: -1;
}

.VPNavBar,
.VPLocalNav.reached-top {
  border-bottom: none;
}
```
