### ISSUE TITLE
`base: "https://example.com/myproject/"` doesn't work for `<a>` links

### ISSUE THREAD

**Issue by jcbhmr** [vuejs/vitepress#3508]
### Describe the bug

When creating a website with GitHub Pages it's common to do something like this to make it agnostic of which user is building the project and previewing it on their own unknown GitHub pages domain in a fork:

```yml
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - id: configure-pages
        uses: actions/configure-pages@v4
      - run: npm run build
        env:
          # BASE_URL=https://user.github.io/myproject/
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist
      - id: deploy-pages
        uses: actions/deploy-pages@v4
```

however, when viewing the page the URL in the `<a>` tags is for some reason missing that second `https://` slash so it gets treated as a relative URL.

![image](https://github.com/vuejs/vitepress/assets/61068799/97e01295-0c94-439b-a089-4c2222e62154)

![image](https://github.com/vuejs/vitepress/assets/61068799/850aa760-98f9-4094-945f-75dd27ba0a62)

but it only happens _sometimes_ for _certain things_ like just links but not `<link>` CSS:

```html
    <link rel="preload stylesheet" href="https://example.com/myproject/assets/style.LijVxLjA.css" as="style">
    
    <script type="module" src="https://example.com/myproject/assets/app.XxNRlDfj.js"></script>
    <link rel="modulepreload" href="https://example.com/myproject/assets/chunks/framework.2pntVdL9.js">
    <link rel="modulepreload" href="https://example.com/myproject/assets/chunks/theme.3Vtt2sMX.js">
    <link rel="modulepreload" href="https://example.com/myproject/assets/index.md.BppFuf7X.lean.js">
```

![image](https://github.com/vuejs/vitepress/assets/61068799/8a3b74a1-169d-48d2-ae72-a7ad5149aee8)

### Reproduction

https://stackblitz.com/edit/vite-maohkd?file=docs%2F.vitepress%2Fconfig.ts

run dev server and hover over the "get started" button and see in the bottom left the wrong URL due to the base url being interpreted wrong

![image](https://github.com/vuejs/vitepress/assets/61068799/1a98a181-1955-40a9-9465-55ae5de9099f)

### Expected behavior

It should be `<a href="https://example.com/myproject/markdown-examples">` NOT `<a href="https:/example.com/myproject/markdown-examples">`

### System Info

```Text
using stackblitz
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
