### ISSUE TITLE
Add CSS class to disable vitepress CSS to avoid conflicts and override

### ISSUE THREAD

**Issue by LouisMazel** [vuejs/vitepress#3652]
### Is your feature request related to a problem? Please describe.

I use Vitepress to document my component library. Sometimes, the style of the components is "overridden" by the Vitepress CSS, or just applied.

For example, with a component using a `<table />` HTMLElement (https://maz-ui.com/components/maz-table), the VitePress CSS is applied to my component and changes its style. **I don't want it.** 

[See CSS file here](https://github.com/vuejs/vitepress/blob/df8753bd927c2b57b9188fb292c1429e9c3c8ab6/src/client/theme-default/styles/components/vp-doc.css#L176)

```css
.vp-doc table {
  display: block;
  border-collapse: collapse;
  margin: 20px 0;
  overflow-x: auto;
}

.vp-doc tr {
  background-color: var(--vp-c-bg);
  border-top: 1px solid var(--vp-c-divider);
  transition: background-color 0.5s;
}

.vp-doc tr:nth-child(2n) {
  background-color: var(--vp-c-bg-soft);
}

.vp-doc th,
.vp-doc td {
  border: 1px solid var(--vp-c-divider);
  padding: 8px 16px;
}

.vp-doc th {
  text-align: left;
  font-size: 14px;
  font-weight: 600;
  color: var(--vp-c-text-2);
  background-color: var(--vp-c-bg-soft);
}

.vp-doc td {
  font-size: 14px;
}
```

### Describe the solution you'd like

I don't want the style to be applied to selected elements.

### Describe alternatives you've considered

As the [tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography) library suggests [here](https://github.com/tailwindlabs/tailwindcss-typography?tab=readme-ov-file#advanced-topics) with the class `not-prose`. 

I propose to add a class like `no-vp-style` or something else to not apply CSS to the HTML element where the class is set and other DOM inside.

```md
## Documentation

<MazTable class="no-vp-style" />
```

With a CSS rule like : 

```css
.vp-doc table:not(:where([class~='no-vp-style'], [class~='no-vp-style'] *)) {
  ...
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
