### ISSUE TITLE
Define the font for "home hero name"

### ISSUE THREAD

**Issue by wuchenchina** [vuejs/vitepress#3678]
```
/**
 * Fonts
 * -------------------------------------------------------------------------- */

:root {
  --vp-font-family-base: LXGWWenKai;  /* normal text font */
  --vp-font-family-mono: LXGWWenKaiMono;  /* code font */
}
```
I have set the overall font like the code above, but I still want "home hero name" to use "Intel" font. How do I do this? Thank you very much!

**Comment by brc-dd** [comment]
```css
.VPHero .name {
  font-family: "Inter var", "Inter", system-ui;
}
```
