### ISSUE TITLE
Set like "images2"

### ISSUE THREAD

**Issue by wuchenchina** [vuejs/vitepress#3681]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/vuejs/vitepress/assets/130227171/df7af0a5-6af3-43a5-8fac-95e983cd31b9)
(The Home Page)

![image](https://github.com/vuejs/vitepress/assets/130227171/0f1d969a-2fb8-45ca-967e-b3c9a7059959)
(The Download Page)

but, the style:
```
  --vp-home-hero-image-background-image: linear-gradient(
    -45deg,
    #186068 50%,
    #00e5ff 50%
  );
```
Conflict with the "Download" page (i.e. Download does not require this style, but the home page does)

### Describe the solution you'd like

Add image2? It means defining some content as images, and the content can be changed through style.css

### Describe alternatives you've considered

Add the following code to "/download/index. md"：

```
<style moudle>
:root {
    --vp-home-hero-image-background-image: none;
}
</style>
```
But it was found that this string of code may affect home (whether it is<style>,<style module>, or<style scoped>)

Maybe it's a problem with my server？

### Additional context

home page:
```
---
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "Cr-DGC"
  text: "不纯粹的石榴石晶体"
  tagline: 基于Minecraft原版制作的PBR材质包
  image: 
    src: "/images/home_logo.png"
  actions:
    - theme: brand
      text: Get Start
      link: /docs/
    - theme: alt
      text: Download
      link: /download/

features:
  - title: XXX
    details:XXX
  - title: XXX
    details: XXX
  - title: XXX
    details: XXX
---

```

Download Page:

```

---
layout: home
prev: false
next: false
sidebar: false

hero:
  name: "Cr-DGC"
  text: "不纯粹的石榴石晶体"
  tagline: 基于Minecraft原版制作的PBR材质包
  image: 
    src: "/images/home_logo.png"
  actions:
    - theme: brand
      text: 下载开源版本
      link: /docs/
    - theme: alt
      text: 下载赞助版本
      link: /download/

---

```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by wuchenchina** [comment]
emmmm，Perhaps it is possible to solve the problem by registering global components?

**Comment by brc-dd** [comment]
Add this to your home page's frontmatter:

```md
---
pageClass: main-home
---
```

Then add that style only for that class:

```css
.main-home {
  --vp-home-hero-image-background-image: linear-gradient(...);
}
```

**Comment by wuchenchina** [comment]
Thank you very much, but I have encountered another problem:

![image](https://github.com/vuejs/vitepress/assets/130227171/be6a967d-73d1-4510-9895-dc81e99d2807)

Is "layout: home" a transparent navigation bar?

Then, I tried to modify it using CSS, as follows:

```
.download {
  background-image: url('/images/bg.png');

  --vp-z-index-footer: 10;
  --vp-z-index-local-nav: 20;
  --vp-z-index-nav: 30;
  --vp-z-index-layout-top: 40;
  --vp-z-index-backdrop: 50;
  --vp-z-index-sidebar: 60;

  --vp-nav-height: 64px;
  --vp-nav-bg-color: var(--vp-c-bg);
  --vp-nav-screen-bg-color: var(--vp-c-bg);
  --vp-nav-logo-height: 24px;

  --vp-local-nav-bg-color: var(--vp-c-bg);
}
```

But to no avail, it's still like this

I'm very sorry for bothering you all today

**Comment by brc-dd** [comment]
```css
.download .VPNavBar {
  background-color: var(--vp-c-bg);
}
```
