### ISSUE TITLE
Hero image don't get included in built website

### ISSUE THREAD

**Issue by kristoferlund** [vuejs/vitepress#3776]
### Describe the bug

The hero image referenced below shows up as expected in development. When building the project, it is not included in the finished build.

```
hero:
  name: "C–ATTS"
  text: "Composite Attestations"
  tagline: Composite attestations are a new type of attestation combining data from multiple sources to form a unified and verifiable credential.
  actions:
    - theme: brand
      text: Composite Attestations?
      link: /docs
    - theme: alt
      text: GitHub
      link: https://github.com/c-atts
  image: /images/diagram.png
```

### Reproduction

GitHub: https://github.com/c-atts/web

Live web: https://catts.run/

### Expected behavior

The image should be included in the build and show up in the hero section on the index page.

### System Info

```Text
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.05 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
    bun: 0.7.3 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 122.1.63.169
    Chrome: 123.0.6312.107
    Edge: 123.0.2420.81
    Safari: 17.4
  npmPackages:
    vitepress: ^1.1.0 => 1.1.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
