### ISSUE TITLE
hydration mismatch with default build

### ISSUE THREAD

**Issue by buingoccong0504** [vuejs/vitepress#3780]
**Describe the bug**
I built and published vitepress pages to my Azure App Service by ASP.Net Core project, but got Hydration completed but contains mismatches error when i review, and the index page and other pages rendered not correctlly. But it runs perfectly on my local within dev mode

![image](https://github.com/vuejs/vitepress/assets/58868728/de1663b3-68c3-439c-a22d-3d6f1818e095)

Correcting render:

![image](https://github.com/vuejs/vitepress/assets/58868728/8d9074c7-bce7-4e86-88a1-087c466a12d1)

**Expected behavior**
All page displays correctlly.

**index.md**
```
---
layout: home
title: SD-LINES デベロッパーポータル

hero:
  name: "SD-LINES ドキュメンテーション"
  tagline: 当社のサービスでウェブサイトの可能性を高めましょう
  actions:
    - theme: brand
      text: 詳しくはこちら
      link: /ja/docs/overview/about

features:
  - title: ユニークで魅力的な広告
    details: 専門的に最適化された広告表示で、訪問者を魅了し、関与させることでウェブサイトの魅力を高めます
  - title: 効果の即時洞察
    details: 詳細な分析により広告のパフォーマンスを即座に把握し、戦略を効果的に調整し、改善することができます
  - title: 迅速かつ正確な検索
    details: ユーザーが製品を迅速かつ簡単に見つけることができるように支援し、これまでにないシームレスなオンラインショッピング体験を提供します。

---

```

**config.mts**
```typescript
import { defineConfig } from 'vitepress'
import { sidebar } from './config/sidebar'

export default defineConfig({
  title: "SD-LINES Developer",
  description: "SD-LINES Developer Documentation",
  head: [
    ['link', { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }]
  ],
  themeConfig: {
    logo: '/logo.svg',
    
    sidebar,
    lastUpdated: {
      text: 'Last updated',
      formatOptions: {
        dateStyle: 'medium',
        timeStyle: 'short'
      }
    },
    search: {
      provider: 'local'
    },
  },
  markdown: {
    lineNumbers: true
  },
  cleanUrls: true,
  lastUpdated: true,
  locales: {
    root: {
      label: '日本語',
      lang: 'ja',
      link: '/ja/',
      themeConfig: { 
        nav: [
          { text: 'Home', link: '/ja/' },
          { text: 'Guides', link: '/ja/docs/overview/about' },
          { text: 'Reference', link: '/ja/reference/market' }
        ],
      }
    },
    en: {
      label: 'English',
      lang: 'en',
      link: '/en/',
      themeConfig: { 
        nav: [
          { text: 'Home', link: '/en/' },
          { text: 'Guides', link: '/en/docs/overview/about' },
          { text: 'Reference', link: '/en/reference/market' }
        ],
      }
    },
  }
})
```

**What I tried**
My site is not using Cloudflare's.
