### ISSUE TITLE
[default theme] Icons on action buttons

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#3783]
### Is your feature request related to a problem? Please describe.

Not problem-related.

### Describe the solution you'd like

Ability to specify an icon for the action buttons, e.g:

```
actions:
    - theme: sponsor
      text: lorem ipsum
      link: https://test.com
      icon:
          src: /test.svg
```

### Describe alternatives you've considered

N/A.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
