### ISSUE TITLE
Github action deploy failed, instructed by the guildance

### ISSUE THREAD

**Issue by TheoppoFish** [vuejs/vitepress#3792]
### Describe the bug

Hi team,

I have tried with a self-hosted gha runner. 

the gha workflow is copy/paste from the guidance, [here](https://vitepress.dev/zh/guide/deploy#github-pages)

Unfortunately,  I failed at the `Upload artifact` stage
![image](https://github.com/vuejs/vitepress/assets/102744674/7262420c-ccb1-4816-bdd9-290dfe3fb295)

Here is my workflow:
```
name: Deploy VitePress site to git pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm install
      - name: Build with VitePress
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: self-hosted
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```

### Reproduction

Re-runed multiple times, but still failed

### Expected behavior

should upload artefacts?

### System Info

```Text
deploying on git page

using self-host runner
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
