### ISSUE TITLE
Custom Chinese font is overridden

### ISSUE THREAD

**Issue by shellRaining** [vuejs/vitepress#3864]
### Describe the bug

<img width="638" alt="image" src="https://github.com/vuejs/vitepress/assets/111564053/b28f2112-61c4-46cd-b581-051e76589d3d">

After updating to the latest version of vitepress, I found that my custom font was overridden. I have specified the font as `LXGW WenKai`, but it is overridden by the higher-level selector `:root:lang(zh)`

### Reproduction

```css
@import url("https://cdn.jsdelivr.net/gh/CMBill/lxgw-wenkai-web/style.css");

:root {
  --vp-font-family-base: "LXGW WenKai";
  --vp-font-family-mono: "LXGW WenKai Mono", monospace;
}
```

The above is the code of my `font.css`.

```typescript
import DefaultTheme from "vitepress/theme-without-fonts";
import "./fonts.css";
import "./custom.css";

export default {
  extends: DefaultTheme,
}
```

This is how I use it

### Expected behavior

Display the correct font and modify the document to provide the latest practices.

### System Info

```Text
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M1
    Memory: 207.77 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 9.0.6 - ~/Library/pnpm/pnpm
    bun: 1.0.18 - ~/.bun/bin/bun
    Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 17.1
  npmPackages:
    vitepress: latest => 1.1.4
```

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
