### ISSUE TITLE
Code for Auto-Generated Sidebar Issues: Pagination Buttons and Highlighting Not Functioning Properly

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#3886]
### Is your feature request related to a problem? Please describe.

I have a code that automatically generates a sidebar based on the folder structure, and it works well. It automatically generates the sidebar every time I build. This code is from the internet (https://www.bilibili.com/read/cv27621286/). I made some modifications based on that.

But after using this code, I have a problem that I can't solve:

- The previous page cannot be displayed correctly in the generated page, and the buttons for the next page always point to the first page.
- In the generated sidebar, clicking on the current page title is valid, but it is not highlighted.

I don’t know much about JavaScript and I’m not sure how to fix this issue.

Here, I'll create a minimal demonstration to illustrate the problem.

I set up a "test" project to explain my problem:

I have a folder: D:\work\test

in test folder, I install vitepress and init:

```
npm add -D vitepress
npx vitepress init
```
I answered like this:
```
◇  Where should VitePress initialize the config?
│  ./docs
```

now I create some folder and move the default md files like this:
```
D:\work>tree test\docs /f
卷 DATA 的文件夹 PATH 列表
卷序列号为 502D-6670
D:\WORK\TEST\DOCS
│  index.md│
├─.vitepress
│     config.mts
│     set_sidebar.mjs
...
│
└─doc1
    └─chapter1
            api-examples.md
            markdown-examples.md
```

In set_sidebar.mjs I have the code to auto generate sidebar
The contents of set_sidebar.mjs:
```javascript
import path from 'node:path'
import fs from 'node:fs'

// 文件根目录
const DIR_PATH = path.resolve('docs')
// 白名单,过滤不是文章的文件和文件夹
const WHITE_LIST = ['index.md', '.vitepress', 'node_modules', '.idea', 'assets']


// 判断是否是文件夹
const isDirectory = (path) => fs.lstatSync(path).isDirectory()

// 取差值
const intersections = (arr1, arr2) => Array.from(new Set(arr1.filter((item) => !new Set(arr2).has(item))))

// 把方法导出直接使用
function getList(params, path1, pathname) {
    // 存放结果
    const res = []
    // 开始遍历params
    for (let file in params) {
        // 拼接目录
        const dir = path.join(path1, params[file])
        // 判断是否assets文件夹
        if (dir.endsWith('.assets')) {
            continue
        }
        // 判断是否是文件夹
        const isDir = isDirectory(dir)
        if (isDir) {
            // 如果是文件夹,读取之后作为下一次递归参数
            const files = fs.readdirSync(dir)
            res.push({
                text: params[file].replace(/^\d+\./g, ''),
                collapsed: false,
                items: getList(files, dir, `${pathname}/${params[file]}`),
            })
        } else {
            // 获取名字
            const name = path.basename(params[file])
            // 排除非 md 文件
            const suffix = path.extname(params[file])
            if (suffix !== '.md') {
                continue
            }
            res.push({
                text: name.replace(/(^\d+\.)|(\.md$)/g, ''),
                link: `${pathname}/${name}`,
            })
        }
    }
    return res
}

export const set_sidebar = (pathname) => {
    // 获取pathname的路径
    const dirPath = path.join(DIR_PATH, pathname)
    // 读取pathname下的所有文件或者文件夹
    const files = fs.readdirSync(dirPath)
    // 过滤掉
    const items = intersections(files, WHITE_LIST)
    // getList 函数后面会讲到
    return getList(items, dirPath, pathname)
}

```

in `config.mts`, I import it and apply it:

```javascript
import { defineConfig } from 'vitepress'
import { set_sidebar } from './set_sidebar.mjs'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "My Awesome Project",
  description: "A VitePress Site",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    sidebar:
      {
        '/doc1/': set_sidebar('doc1'),
      },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  }
})
```

I change the index.md to corrent link:
```
---
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "My Awesome Project"
  text: "A VitePress Site"
  tagline: My great project tagline
  actions:
    - theme: brand
      text: Markdown Examples
      link: /doc1/chapter1/markdown-examples
    - theme: alt
      text: API Examples
      link: /doc1/chapter1/api-examples

features:
  - title: Feature A
    details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
  - title: Feature B
    details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
  - title: Feature C
    details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
---
```

now, `npm run docs:dev`:
![PixPin_2024-05-13_17-09-35](https://github.com/vuejs/vitepress/assets/57745184/18d2310e-42c2-4f63-9a58-efd854b39795)

### Describe the solution you'd like

I hope someone can guide me on how to solve this issue. I want the page navigation buttons for the previous and next pages to correctly point to the right documents, and for the sidebar to highlight the current page.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
