### ISSUE TITLE
Deploy to gitlab - vitepress: not found

### ISSUE THREAD

**Issue by XinleZhou2018** [vuejs/vitepress#3887]
### Describe the bug

When I commit my code to gitlab, it says: vitepress: not found
![1](https://github.com/vuejs/vitepress/assets/39542071/72c071c9-f608-413b-b687-ad762333d0f3)

this is my .gitlab-ci.yml 
```
image: node:18
pages:
  cache:
    paths:
      - node_modules/
  script:
    # - apk add git # 如果你使用的是像 alpine 这样的小型 docker 镜像，并且启用了 lastUpdated，请取消注释
    - npm install
    - npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - main
```

why? is it because gitlab pages setting error? how to set?
![2](https://github.com/vuejs/vitepress/assets/39542071/96dfeb8e-a824-4a4a-8e1d-267404b1426d)

### Reproduction

see above

### Expected behavior

see above

### System Info

```Text
see above
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
