### ISSUE TITLE
when the length of the Math Equation is too long

### ISSUE THREAD

**Issue by DrAugus** [vuejs/vitepress#3914]
### Is your feature request related to a problem? Please describe.

If the length of a mathematical formula is too long and exceeds the page width, can a scrollbar be added to the `mjx-container`?

<https://github.com/vuejs/vitepress/blob/49dbfb4ea37e22f38946218e9beda5b511713ce1/src/client/theme-default/styles/base.css#L244-L247>

<details><summary>phone screenshot</summary>

![img_v3_02b6_900219f1-55ba-4b50-95cd-f3d987c9a21g](https://github.com/vuejs/vitepress/assets/34206897/80adcbca-5a67-4d40-a0e7-7360c435122d)

</details>

### Describe the solution you'd like

css add

```css
mjx-container {
  display: inline-block;
  margin: auto 2px -2px;
  overflow-x: auto;
  max-width: 100%;
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
