### ISSUE TITLE
[Feature request] Ability to use images in customer containers' custom title

### ISSUE THREAD

**Issue by thdoan** [vuejs/vitepress#4214]
### Is your feature request related to a problem? Please describe.

Sometimes emojis don't cut it, so it would be awesome to have the ability to use images in customer containers' custom title.

### Describe the solution you'd like

```
::: tip ![custom tip icon](/tip.svg) TIP
This is a tip.
:::
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by rvanhorn** [comment]
This is something I'd also like to see added. 

In the meantime ,you can manually add an icon via CSS.

```css
.tip > .custom-block-title::before {
    content: '';
    display: inline-block;
    width: 1.25rem;
    height: 1.25rem;
    background-color: var(--vp-c-text-1);
    -webkit-mask-image: url('/images/info.svg');
    mask-image: url('/images/info.svg');
    -webkit-mask-size: contain;
    mask-size: contain;
    -webkit-mask-repeat: no-repeat;
    mask-repeat: no-repeat;
    margin-right: 0.5rem;
    vertical-align: middle;
}
```
