### ISSUE TITLE
Default theme's `VPFlyout` does not show without JavaScript

### ISSUE THREAD

**Issue by BeiyanYunyi** [vuejs/vitepress#4224]
### Describe the bug

Default theme's `VPFlyout` has these css:

```css
.VPFlyout:hover .menu,
.button[aria-expanded="true"] + .menu {
  opacity: 1;
  visibility: visible;
  transform: translateY(0);
}

.button[aria-expanded="false"] + .menu {
  opacity: 0;
  visibility: hidden;
  transform: translateY(0);
}
```

According to [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity), the selector ` ` and `+` have the same specificity, which means the rule that comes next will override the rule that comes first. The result is, when JavaScript is disabled, the `aria-expanded` property will keep as `false`, and the contents of `VPFlyout` will never show.

### Reproduction

Just go to [the official docs site](https://vitepress.dev/), disable JavaScript. Move mouse cursor over any `VPFlyout` components.

### Expected behavior

The contents of `VPFlyout` should show with no JavaScript.

### System Info

```Text
System:
    OS: Linux 6.10 Arch Linux
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 22.07 GB / 31.13 GB
    Container: Yes
    Shell: 3.7.1 - /usr/bin/fish
  Binaries:
    Node: 20.17.0 - ~/.nix-profile/bin/node
    npm: 10.8.2 - ~/.nix-profile/bin/npm
    pnpm: 9.9.0 - ~/.nix-profile/bin/pnpm
    bun: 1.1.29 - /usr/bin/bun
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
