### ISSUE TITLE
Github action example with actions/cache usage

### ISSUE THREAD

**Issue by kravetsone** [vuejs/vitepress#4372]
continues of https://github.com/shikijs/shiki/issues/840

We have[ `.vitepress/cache` directory](https://vitepress.dev/reference/site-config#cachedir) which contains some files which vitepress uses as cache.

Does we should to include it in our workflow as step with `actions/cache`? For example:
```yml
- uses: actions/cache@v4
              with:
                  path: ./docs/.vitepress/cache
                  key: ${{ runner.os }}-vitepress-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('docs/**') }}
                  restore-keys: |
                      ${{ runner.os }}-vitepress
```

What are the best practices or pros and cons of using `actions/cache` on `.vitepress/cache` folder?

It would be great to include this in documentation

For now [deploy#github-pages](https://vitepress.dev/guide/deploy#github-pages) don't use it. Its just missed or it have some side-effects?
