### ISSUE TITLE
Intermittent GitHub Pages Issue: Showing Root README after Commit

### ISSUE THREAD

**Issue by yilinxia** [vuejs/vitepress#4631]
Hi,

We’ve been encountering an issue with our GitHub Pages site where, after committing to GitHub, the site occasionally doesn’t behave as expected. Sometimes it works fine, but other times it displays the root folder's README file instead of the actual content, and no errors are shown in the browser console.

**Context:**

The site works perfectly locally.

**Steps to Reproduce:**
1. Commit changes to the repository.
2. Push the changes to GitHub.
3. Visit the deployed GitHub Pages site.
4. Observe that sometimes the website works fine, but other times the root folder's README is displayed.

**Environment:**
1. VitePress version: 1.6.3
2. GitHub Pages URL: https://logica-web.github.io/

**GitHub Action Workflow:**
```
# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy Logica site to Pages

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      # - uses: pnpm/action-setup@v3 # Uncomment this block if you're using pnpm
      #   with:
      #     version: 9 # Not needed if you've set "packageManager" in package.json
      # - uses: oven-sh/setup-bun@v1 # Uncomment this if you're using Bun
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # or pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci # or pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: npm run docs:build # or pnpm docs:build / yarn docs:build / bun run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```

Thanks for the help!
