### ISSUE TITLE
Default theme nav bar background does not extend fully

### ISSUE THREAD

**Issue by NonSpicyBurrito** [vuejs/vitepress#4653]
### Describe the bug

Using default theme, nav bar background does not extend fully to the right in widescreen mode, causing customizing with `--vp-nav-bg-color` to be unusable.

### Reproduction

Create a project with default theme with customized CSS:
```css
:root {
    --vp-nav-bg-color: red;
}
```
Observe that nav bar background does not extend fully to the right in widescreen mode:
![Image](https://github.com/user-attachments/assets/1a582643-695b-40e1-9744-b53c91c1c004)

### Expected behavior

Nav bar background to extend fully.

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Memory: 2.24 GB / 11.90 GB
  Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 134.0.6998.166
    Edge: Chromium (127.0.2651.105)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    vitepress: ^2.0.0-alpha.4 => 2.0.0-alpha.4
```

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [x] Read the [docs](https://vitepress.dev).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by NonSpicyBurrito** [comment]
It also does not fully extend to the left if the screen is over the largest breakpoint.

**Comment by brc-dd** [comment]
Use something like

```css
.VPNav {
    --vp-nav-bg-color: red;
    background-color: var(--vp-nav-bg-color);

    .title {
        border-color: var(--vp-nav-bg-color) !important;
    }
}
```
