### ISSUE TITLE
Cannot visit vitepress online after deploying files under `docs/.vitepress/dist/` to my server

### ISSUE THREAD

**Issue by sooia** [vuejs/vitepress#469]
### Describe the bug

I upload the files under the path `docs/.vitepress/dist/` to my website, but I cannot visit the vitepress online.
![image](https://user-images.githubusercontent.com/92929085/145968789-5e353eaf-b8e6-41a1-a95a-142a1d9bb41c.png)
The uploaded files is here is reproduce the behavior (`pnpm docs-build`) locally.
![image](https://user-images.githubusercontent.com/92929085/145972722-f2d1456b-0884-4ec0-a4fd-13484292034f.png)

### Reproduction
To reproduce the behavior, run `pnpm docs-build` and upload files under `docs/.vitepress/dist/` to the server(website)'s default (root) path.
![image](https://user-images.githubusercontent.com/92929085/145972722-f2d1456b-0884-4ec0-a4fd-13484292034f.png)
https://vitepress.vuejs.org/guide/deploy#building-the-docs
Or Upload the file under the path of `docs/.vitepress/dist/` to the web server, with Github Actions:
```
name: Deploy

on:
  push:
    branches: 
      - main
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  build-production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm docs-build

      - name: Deploy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'docs/.vitepress/dist/*'
          target: '/www/wwwroot/jun.sh/main'
          strip_components: 3
          rm: 'true'
```

### Expected behavior

Visit the vitepress website online correctly.

### System Info

```shell
pnpm - 6.15.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
