### ISSUE TITLE
Code Block Highlighting is broken

### ISSUE THREAD

**Issue by AzonInc** [vuejs/vitepress#4729]
### Describe the bug

Heya, I'm experiencing a weird issue with Code Blocks which started by the beginning of this year after updating to a newer version from `1.3.2`.
The Highlighting used to work fine with an older version of vitepress but now it seems to be broken.

Result right now:
![Image](https://github.com/user-attachments/assets/298c99bb-73a4-4849-beb1-5070d6637f00)
![Image](https://github.com/user-attachments/assets/9e20ce9e-561c-47de-b55c-87f9223688a5)

The affected file is located here: https://github.com/AzonInc/Doorman/blob/master/docs/en/guide/firmware/additions.md

### Reproduction

Create a Code Block using this MD:

```yaml
binary_sensor: // [!code ++] // [!code focus]
  - platform: tc_bus // [!code ++] // [!code focus]
    name: "Custom Command" // [!code ++] // [!code focus]
    type: open_door // [!code ++] // [!code focus]
    address: 0 // [!code ++] // [!code focus]
    web_server: // [!code ++] // [!code focus]
      sorting_group_id: sorting_group_listeners // [!code ++] // [!code focus]
```

### Expected behavior

// [!code ++] // [!code focus] shouldn't be visible and also not randomly applied.

### System Info

```Text
System:
    OS: Windows 11 10.0.26120
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 9.89 GB / 31.91 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 6.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 135.0.7049.116
    Edge: Chromium (136.0.3240.29)
  npmPackages:
    vitepress: ^2.0.0-alpha.5 => 2.0.0-alpha.5
```

### Additional context

Am I doing anything wrong or is it really broken?

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [x] Read the [docs](https://vitepress.dev).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
You should use yaml style comments:

```md
```yaml
binary_sensor: # [!code ++] [!code focus]
  - platform: tc_bus # [!code ++] [!code focus]
    name: "Custom Command" # [!code ++] [!code focus]
    type: open_door # [!code ++] [!code focus]
    address: 0 # [!code ++] [!code focus]
    web_server: # [!code ++] [!code focus]
      sorting_group_id: sorting_group_listeners # [!code ++] [!code focus]
```
```

**Comment by AzonInc** [comment]
Thanks a lot for clarification :) That worked.
However i still have a problem with comments itself.

Example:
```yaml
# Extend the doorbell_pattern event entity [!code ++] [!code focus]
# Add a new apartment_special event type [!code ++] [!code focus]
event: # [!code ++] [!code focus]
  - id: !extend apartment_doorbell_pattern # [!code ++] [!code focus]
    event_types: # [!code ++] [!code focus]
      - "apartment_special" # [!code ++] [!code focus]

# Extend the apartment_doorbell / entrance_doorbell entity [!code ++] [!code focus]
# and add your new special pattern [!code ++] [!code focus]
binary_sensor: # [!code ++] [!code focus]
  - id: !extend apartment_doorbell # [!code ++] [!code focus]
    on_multi_click: # [!code ++] [!code focus]
      # Special Pattern [!code ++] [!code focus]
      - timing: # [!code ++] [!code focus]
          # Press twice with no more than one second between each press. [!code ++] [!code focus]
          - ON for at most 0.5s # [!code ++] [!code focus]
          - OFF for at most 1s # [!code ++] [!code focus]
          - ON for at most 0.5s # [!code ++] [!code focus]
          - OFF for at least 2s # [!code ++] [!code focus]
        then: # [!code ++] [!code focus]
          - logger.log: "Special pattern detected!" # [!code ++] [!code focus]
          - event.trigger: # [!code ++] [!code focus]
              id: apartment_doorbell_pattern # [!code ++] [!code focus]
              # Use the previously defined new event type here [!code ++] [!code focus]
              event_type: apartment_special # [!code ++] [!code focus]
```

Results in:

![Image](https://github.com/user-attachments/assets/491efa5d-6499-48bb-962c-49522783b8c6)

**Comment by brc-dd** [comment]
Hmm, seems like https://github.com/shikijs/shiki/issues/934 didn't handle all cases. For now you can do:

```yaml
```yaml
# Extend the doorbell_pattern event entity // [!code ++] [!code focus]
# Add a new apartment_special event type // [!code ++] [!code focus]
event: # [!code ++] [!code focus]
  - id: !extend apartment_doorbell_pattern # [!code ++] [!code focus]
    event_types: # [!code ++] [!code focus]
      - "apartment_special" # [!code ++] [!code focus]

# Extend the apartment_doorbell / entrance_doorbell entity // [!code ++] [!code focus]
# and add your new special pattern // [!code ++] [!code focus]
binary_sensor: # [!code ++] [!code focus]
  - id: !extend apartment_doorbell # [!code ++] [!code focus]
    on_multi_click: # [!code ++] [!code focus]
      # Special Pattern // [!code ++] [!code focus]
      - timing: # [!code ++] [!code focus]
          # Press twice with no more than one second between each press. // [!code ++] [!code focus]
          - ON for at most 0.5s # [!code ++] [!code focus]
          - OFF for at most 1s # [!code ++] [!code focus]
          - ON for at most 0.5s # [!code ++] [!code focus]
          - OFF for at least 2s # [!code ++] [!code focus]
        then: # [!code ++] [!code focus]
          - logger.log: "Special pattern detected!" # [!code ++] [!code focus]
          - event.trigger: # [!code ++] [!code focus]
              id: apartment_doorbell_pattern # [!code ++] [!code focus]
              # Use the previously defined new event type here // [!code ++] [!code focus]
              event_type: apartment_special # [!code ++] [!code focus]
```

I'll create an issue on shiki repo.
