### ISSUE TITLE
vite config server.allowedHosts is not working

### ISSUE THREAD

**Issue by donflavour** [vuejs/vitepress#4774]
### Describe the bug

I'm trying to deploy vitepress to k8s and im stucked with the following error message: `Blocked request. This host ("xxx") is not allowed.
To allow this host, add "xxx" to server.allowedHosts in vite.config.js.`

After some research I've added the vite config to the config.mts:
```
import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "xxx",
  description: "xxx",
  vite: {
    server: {
      allowedHosts: true,
    },
  },
})
```

I also tried to set the allowedHost via ENV var but without success:
```
        env:
        - name: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
          value: ".xxx"
```

I start the server with `        command: ['npm', 'run', 'docs:dev', '--','--host']`

According to the [docs](https://vitepress.dev/reference/site-config#vite), my example should work or do I miss anything?

Many Thanks

### Reproduction

Take config.mts above and try to access it with different host.

### Expected behavior

After setting allowedHosts: true I should be capable to connect

### System Info

```Text
IMG: node:22-alpine
```

### Additional context

Trying to deploy to k8s:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docu
  template:
    metadata:
      labels:
        app: docu
    spec:
      containers:
      - name: bcon-docu
        image: documentation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
          value: ".xxx"
        command: ['npm', 'run', 'docs:dev', '--','--host']
```

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [x] Read the [docs](https://vitepress.dev).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
