### ISSUE TITLE
`style module` is not scooped when using body

### ISSUE THREAD

**Issue by Xenos112** [vuejs/vitepress#4777]
### Describe the bug

i was building a docs for react and i added this css to showcase a hook
```css
<style module>

body {
    height: 120vh;
    width: 120vw;
}

</style>
```

in development it was behaving as normal but once i built the project i got the extra width in all pages

### Reproduction

for me adding this css broke the whole thing
```css
<style module>

body {
    height: 120vh;
    width: 120vw;
}

</style>
```

here is a [live website](https://use-reacty.vercel.app/), and here is the [full code](https://github.com/Xenos112/use-reacty/tree/main/docs/hooks/use-window-scroll)

### Expected behavior

i should be only scooped to that page not applied globaly

### System Info

```Text
System:
    OS: Linux 6.14 Arch Linux
    CPU: (8) x64 AMD Ryzen 3 5400U with Radeon Graphics
    Memory: 2.09 GB / 6.59 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 24.1.0 - /usr/bin/node
    npm: 11.4.1 - /usr/bin/npm
    pnpm: 10.11.1 - /usr/bin/pnpm
    bun: 1.2.15 - /usr/bin/bun
```

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [x] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [x] Read the [docs](https://vitepress.dev).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
https://vuejs.org/api/sfc-css-features#css-modules , https://github.com/css-modules/css-modules/blob/master/docs/composition.md#exceptions

If you want to apply global styles, then you need to do:

```css
:global(body) {
  height: 120vh;
  width: 120vw;
}
```

If you want to apply it only to one page, you can do something like this:

```md
---
pageClass: foo
---

your content ...

<style>
body:has(.Layout.foo) {
  height: 120vh;
  width: 120vw;
}
</style>
```

^ `:has` is not supported in older browsers. You'll need to use JS if you want to support those too. Something like this will work:

```md
your content ...

<script setup>
import { useStyleTag } from '@vueuse/core'

useStyleTag(`\
body {
  height: 120vh;
  width: 120vw;
}`)
</script>
```
