### ISSUE TITLE
[next] Navbar background not being blurred on Firefox

### ISSUE THREAD

**Issue by kiaking** [vuejs/vitepress#652]
OK what css prefix do we need for Firefox 🤔 

![unknown](https://user-images.githubusercontent.com/3753672/170214590-f439c709-d1a5-4062-b493-436e36d293ef.png)

**Comment by Akryum** [comment]
```css
@supports not (backdrop-filter: blur(8px)) {
  .content {
    background: rgba(255 255 255 / .97);
  }
}
```
