### ISSUE TITLE
navbar menu may exceeds the screen

### ISSUE THREAD

**Issue by likui628** [vuejs/vitepress#988]
### Is your feature request related to a problem? Please describe.

If there are many navbar menus or the users have a low-resolution screen, 
it is supposed that the navbar menus may succeed the screen height.
![image](https://user-images.githubusercontent.com/90845831/179002991-10913205-f531-4fbe-905f-c40bb20c0b28.png)

### Describe the solution you'd like

add max-height and overflow-y properties 
https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPMenu.vue
```css
.VPMenu {
  /** +++ **/
  max-height: 90vh;
  overflow-y: scroll;
 / ** +++ **/
  border-radius: 12px;
  padding: 12px;
  min-width: 128px;
  border: 1px solid var(--vp-c-divider-light);
  background-color: var(--vp-c-bg);
  box-shadow: var(--vp-shadow-3);
  transition: background-color 0.5s;
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
